# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIv12-Jul15-2016.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 753)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.runAllTab = QtWidgets.QWidget()
        self.runAllTab.setObjectName("runAllTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.runAllTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.runAllHeaderLabel = QtWidgets.QLabel(self.runAllTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.runAllHeaderLabel.setFont(font)
        self.runAllHeaderLabel.setWordWrap(True)
        self.runAllHeaderLabel.setObjectName("runAllHeaderLabel")
        self.gridLayout_7.addWidget(self.runAllHeaderLabel, 0, 0, 1, 6)
        self.runAllBEViewerButton = QtWidgets.QPushButton(self.runAllTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAllBEViewerButton.sizePolicy().hasHeightForWidth())
        self.runAllBEViewerButton.setSizePolicy(sizePolicy)
        self.runAllBEViewerButton.setObjectName("runAllBEViewerButton")
        self.gridLayout_7.addWidget(self.runAllBEViewerButton, 1, 3, 1, 2)
        self.runAllImageFileLabel = QtWidgets.QLabel(self.runAllTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllImageFileLabel.setFont(font)
        self.runAllImageFileLabel.setObjectName("runAllImageFileLabel")
        self.gridLayout_7.addWidget(self.runAllImageFileLabel, 2, 0, 1, 1)
        self.runAllImageFileToolButton = QtWidgets.QToolButton(self.runAllTab)
        self.runAllImageFileToolButton.setObjectName("runAllImageFileToolButton")
        self.gridLayout_7.addWidget(self.runAllImageFileToolButton, 3, 5, 1, 1)
        self.runAllBEDirectoryToolButton = QtWidgets.QToolButton(self.runAllTab)
        self.runAllBEDirectoryToolButton.setObjectName("runAllBEDirectoryToolButton")
        self.gridLayout_7.addWidget(self.runAllBEDirectoryToolButton, 5, 5, 1, 1)
        self.runAllOutputDirToolButton = QtWidgets.QToolButton(self.runAllTab)
        self.runAllOutputDirToolButton.setObjectName("runAllOutputDirToolButton")
        self.gridLayout_7.addWidget(self.runAllOutputDirToolButton, 7, 5, 1, 1)
        self.runAllConfigToolButton = QtWidgets.QToolButton(self.runAllTab)
        self.runAllConfigToolButton.setObjectName("runAllConfigToolButton")
        self.gridLayout_7.addWidget(self.runAllConfigToolButton, 9, 5, 1, 1)
        self.runAllTextEditLabel = QtWidgets.QLabel(self.runAllTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllTextEditLabel.setFont(font)
        self.runAllTextEditLabel.setObjectName("runAllTextEditLabel")
        self.gridLayout_7.addWidget(self.runAllTextEditLabel, 13, 0, 1, 1)
        self.runAllProgress = QtWidgets.QProgressBar(self.runAllTab)
        self.runAllProgress.setMaximum(1)
        self.runAllProgress.setProperty("value", -1)
        self.runAllProgress.setObjectName("runAllProgress")
        self.gridLayout_7.addWidget(self.runAllProgress, 15, 0, 1, 1)
        self.runAllClose = QtWidgets.QPushButton(self.runAllTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAllClose.sizePolicy().hasHeightForWidth())
        self.runAllClose.setSizePolicy(sizePolicy)
        self.runAllClose.setObjectName("runAllClose")
        self.gridLayout_7.addWidget(self.runAllClose, 15, 1, 1, 1)
        self.runAllCancel = QtWidgets.QPushButton(self.runAllTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAllCancel.sizePolicy().hasHeightForWidth())
        self.runAllCancel.setSizePolicy(sizePolicy)
        self.runAllCancel.setObjectName("runAllCancel")
        self.gridLayout_7.addWidget(self.runAllCancel, 15, 2, 1, 2)
        self.runAllRun = QtWidgets.QPushButton(self.runAllTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAllRun.sizePolicy().hasHeightForWidth())
        self.runAllRun.setSizePolicy(sizePolicy)
        self.runAllRun.setObjectName("runAllRun")
        self.gridLayout_7.addWidget(self.runAllRun, 15, 4, 1, 1)
        self.runAllTextEdit = QtWidgets.QTextEdit(self.runAllTab)
        self.runAllTextEdit.setAutoFillBackground(True)
        self.runAllTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.runAllTextEdit.setObjectName("runAllTextEdit")
        self.gridLayout_7.addWidget(self.runAllTextEdit, 14, 0, 1, 5)
        self.runAllConfigLineEdit = QtWidgets.QLineEdit(self.runAllTab)
        self.runAllConfigLineEdit.setObjectName("runAllConfigLineEdit")
        self.gridLayout_7.addWidget(self.runAllConfigLineEdit, 9, 0, 1, 5)
        self.runAllLineEditLabel = QtWidgets.QLineEdit(self.runAllTab)
        self.runAllLineEditLabel.setObjectName("runAllLineEditLabel")
        self.gridLayout_7.addWidget(self.runAllLineEditLabel, 7, 0, 1, 5)
        self.runAllBEDirectoryLineEdit = QtWidgets.QLineEdit(self.runAllTab)
        self.runAllBEDirectoryLineEdit.setObjectName("runAllBEDirectoryLineEdit")
        self.gridLayout_7.addWidget(self.runAllBEDirectoryLineEdit, 5, 0, 1, 5)
        self.runAllImageFileLineEdit = QtWidgets.QLineEdit(self.runAllTab)
        self.runAllImageFileLineEdit.setText("")
        self.runAllImageFileLineEdit.setMaxLength(0)
        self.runAllImageFileLineEdit.setObjectName("runAllImageFileLineEdit")
        self.gridLayout_7.addWidget(self.runAllImageFileLineEdit, 3, 0, 1, 5)
        self.runAllBEDirectoryLabel = QtWidgets.QLabel(self.runAllTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllBEDirectoryLabel.setFont(font)
        self.runAllBEDirectoryLabel.setObjectName("runAllBEDirectoryLabel")
        self.gridLayout_7.addWidget(self.runAllBEDirectoryLabel, 4, 0, 1, 5)
        self.runAllOutputDirLabel = QtWidgets.QLabel(self.runAllTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllOutputDirLabel.setFont(font)
        self.runAllOutputDirLabel.setObjectName("runAllOutputDirLabel")
        self.gridLayout_7.addWidget(self.runAllOutputDirLabel, 6, 0, 1, 5)
        self.runaAllBEDescriptorLabel = QtWidgets.QLabel(self.runAllTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.runaAllBEDescriptorLabel.setFont(font)
        self.runaAllBEDescriptorLabel.setWordWrap(True)
        self.runaAllBEDescriptorLabel.setObjectName("runaAllBEDescriptorLabel")
        self.gridLayout_7.addWidget(self.runaAllBEDescriptorLabel, 1, 0, 1, 2)
        self.runAllConfigLabel = QtWidgets.QLabel(self.runAllTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllConfigLabel.setFont(font)
        self.runAllConfigLabel.setObjectName("runAllConfigLabel")
        self.gridLayout_7.addWidget(self.runAllConfigLabel, 8, 0, 1, 5)
        self.runAllDisableFiwalkXLSXCheck = QtWidgets.QCheckBox(self.runAllTab)
        self.runAllDisableFiwalkXLSXCheck.setObjectName("runAllDisableFiwalkXLSXCheck")
        self.gridLayout_7.addWidget(self.runAllDisableFiwalkXLSXCheck, 10, 0, 1, 5)
        self.runAllDisableAnnotatedXLSXCheck = QtWidgets.QCheckBox(self.runAllTab)
        self.runAllDisableAnnotatedXLSXCheck.setObjectName("runAllDisableAnnotatedXLSXCheck")
        self.gridLayout_7.addWidget(self.runAllDisableAnnotatedXLSXCheck, 11, 0, 1, 5)
        self.runAllDisablePDFCheck = QtWidgets.QCheckBox(self.runAllTab)
        self.runAllDisablePDFCheck.setObjectName("runAllDisablePDFCheck")
        self.gridLayout_7.addWidget(self.runAllDisablePDFCheck, 12, 0, 1, 5)
        self.tabWidget.addTab(self.runAllTab, "")
        self.runAllAutoTab = QtWidgets.QWidget()
        self.runAllAutoTab.setObjectName("runAllAutoTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.runAllAutoTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.runAllAutoHeaderLabel = QtWidgets.QLabel(self.runAllAutoTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.runAllAutoHeaderLabel.setFont(font)
        self.runAllAutoHeaderLabel.setWordWrap(True)
        self.runAllAutoHeaderLabel.setObjectName("runAllAutoHeaderLabel")
        self.gridLayout_6.addWidget(self.runAllAutoHeaderLabel, 0, 0, 1, 5)
        self.runAllAutoDescriptorLabel = QtWidgets.QLabel(self.runAllAutoTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.runAllAutoDescriptorLabel.setFont(font)
        self.runAllAutoDescriptorLabel.setWordWrap(True)
        self.runAllAutoDescriptorLabel.setObjectName("runAllAutoDescriptorLabel")
        self.gridLayout_6.addWidget(self.runAllAutoDescriptorLabel, 1, 0, 1, 4)
        self.runAllAutoImageFileLabel = QtWidgets.QLabel(self.runAllAutoTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllAutoImageFileLabel.setFont(font)
        self.runAllAutoImageFileLabel.setObjectName("runAllAutoImageFileLabel")
        self.gridLayout_6.addWidget(self.runAllAutoImageFileLabel, 2, 0, 1, 1)
        self.runAllAutoImageFileToolButton = QtWidgets.QToolButton(self.runAllAutoTab)
        self.runAllAutoImageFileToolButton.setObjectName("runAllAutoImageFileToolButton")
        self.gridLayout_6.addWidget(self.runAllAutoImageFileToolButton, 3, 4, 1, 1)
        self.runAllAutoOutputDirCheckBox = QtWidgets.QCheckBox(self.runAllAutoTab)
        self.runAllAutoOutputDirCheckBox.setObjectName("runAllAutoOutputDirCheckBox")
        self.gridLayout_6.addWidget(self.runAllAutoOutputDirCheckBox, 4, 0, 1, 1)
        self.runAllAutoOutputDirLabel = QtWidgets.QLabel(self.runAllAutoTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllAutoOutputDirLabel.setFont(font)
        self.runAllAutoOutputDirLabel.setObjectName("runAllAutoOutputDirLabel")
        self.gridLayout_6.addWidget(self.runAllAutoOutputDirLabel, 5, 0, 1, 2)
        self.runAllAutoOutputDirToolButton = QtWidgets.QToolButton(self.runAllAutoTab)
        self.runAllAutoOutputDirToolButton.setObjectName("runAllAutoOutputDirToolButton")
        self.gridLayout_6.addWidget(self.runAllAutoOutputDirToolButton, 6, 4, 1, 1)
        self.runAllAutoDisableFiwalkXLSXCheck = QtWidgets.QCheckBox(self.runAllAutoTab)
        self.runAllAutoDisableFiwalkXLSXCheck.setObjectName("runAllAutoDisableFiwalkXLSXCheck")
        self.gridLayout_6.addWidget(self.runAllAutoDisableFiwalkXLSXCheck, 7, 0, 1, 2)
        self.runAllAutoDisableAnnotatedXLSXCheck = QtWidgets.QCheckBox(self.runAllAutoTab)
        self.runAllAutoDisableAnnotatedXLSXCheck.setObjectName("runAllAutoDisableAnnotatedXLSXCheck")
        self.gridLayout_6.addWidget(self.runAllAutoDisableAnnotatedXLSXCheck, 8, 0, 1, 2)
        self.runAllAutoDisablePDFCheck = QtWidgets.QCheckBox(self.runAllAutoTab)
        self.runAllAutoDisablePDFCheck.setObjectName("runAllAutoDisablePDFCheck")
        self.gridLayout_6.addWidget(self.runAllAutoDisablePDFCheck, 9, 0, 1, 2)
        self.runAllAutoTextEditLabel = QtWidgets.QLabel(self.runAllAutoTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllAutoTextEditLabel.setFont(font)
        self.runAllAutoTextEditLabel.setObjectName("runAllAutoTextEditLabel")
        self.gridLayout_6.addWidget(self.runAllAutoTextEditLabel, 10, 0, 1, 1)
        self.runAllAutoProgress = QtWidgets.QProgressBar(self.runAllAutoTab)
        self.runAllAutoProgress.setMaximum(1)
        self.runAllAutoProgress.setProperty("value", -1)
        self.runAllAutoProgress.setObjectName("runAllAutoProgress")
        self.gridLayout_6.addWidget(self.runAllAutoProgress, 12, 0, 1, 1)
        self.runAllAutoClose = QtWidgets.QPushButton(self.runAllAutoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAllAutoClose.sizePolicy().hasHeightForWidth())
        self.runAllAutoClose.setSizePolicy(sizePolicy)
        self.runAllAutoClose.setObjectName("runAllAutoClose")
        self.gridLayout_6.addWidget(self.runAllAutoClose, 12, 1, 1, 1)
        self.runAllAutoCancel = QtWidgets.QPushButton(self.runAllAutoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAllAutoCancel.sizePolicy().hasHeightForWidth())
        self.runAllAutoCancel.setSizePolicy(sizePolicy)
        self.runAllAutoCancel.setObjectName("runAllAutoCancel")
        self.gridLayout_6.addWidget(self.runAllAutoCancel, 12, 2, 1, 1)
        self.runAllAutoRun = QtWidgets.QPushButton(self.runAllAutoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAllAutoRun.sizePolicy().hasHeightForWidth())
        self.runAllAutoRun.setSizePolicy(sizePolicy)
        self.runAllAutoRun.setObjectName("runAllAutoRun")
        self.gridLayout_6.addWidget(self.runAllAutoRun, 12, 3, 1, 1)
        self.runAllAutoImageFileLineEdit = QtWidgets.QLineEdit(self.runAllAutoTab)
        self.runAllAutoImageFileLineEdit.setMaxLength(0)
        self.runAllAutoImageFileLineEdit.setObjectName("runAllAutoImageFileLineEdit")
        self.gridLayout_6.addWidget(self.runAllAutoImageFileLineEdit, 3, 0, 1, 4)
        self.runAllAutoOutputDirLineEdit = QtWidgets.QLineEdit(self.runAllAutoTab)
        self.runAllAutoOutputDirLineEdit.setObjectName("runAllAutoOutputDirLineEdit")
        self.gridLayout_6.addWidget(self.runAllAutoOutputDirLineEdit, 6, 0, 1, 4)
        self.runAllAutoTextEdit = QtWidgets.QTextEdit(self.runAllAutoTab)
        self.runAllAutoTextEdit.setAutoFillBackground(True)
        self.runAllAutoTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.runAllAutoTextEdit.setObjectName("runAllAutoTextEdit")
        self.gridLayout_6.addWidget(self.runAllAutoTextEdit, 11, 0, 1, 4)
        self.tabWidget.addTab(self.runAllAutoTab, "")
        self.fiwalkTab = QtWidgets.QWidget()
        self.fiwalkTab.setObjectName("fiwalkTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fiwalkTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fiwalkHeaderLabel = QtWidgets.QLabel(self.fiwalkTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.fiwalkHeaderLabel.setFont(font)
        self.fiwalkHeaderLabel.setWordWrap(True)
        self.fiwalkHeaderLabel.setObjectName("fiwalkHeaderLabel")
        self.gridLayout_3.addWidget(self.fiwalkHeaderLabel, 0, 0, 1, 5)
        self.fiwalkImageFileLabel = QtWidgets.QLabel(self.fiwalkTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiwalkImageFileLabel.setFont(font)
        self.fiwalkImageFileLabel.setObjectName("fiwalkImageFileLabel")
        self.gridLayout_3.addWidget(self.fiwalkImageFileLabel, 1, 0, 1, 1)
        self.fiwalkImageFileToolButton = QtWidgets.QToolButton(self.fiwalkTab)
        self.fiwalkImageFileToolButton.setObjectName("fiwalkImageFileToolButton")
        self.gridLayout_3.addWidget(self.fiwalkImageFileToolButton, 2, 4, 1, 1)
        self.fiwalkOutputFileCheckBox = QtWidgets.QCheckBox(self.fiwalkTab)
        self.fiwalkOutputFileCheckBox.setObjectName("fiwalkOutputFileCheckBox")
        self.gridLayout_3.addWidget(self.fiwalkOutputFileCheckBox, 3, 0, 1, 1)
        self.fiwalkOutputFileLabel = QtWidgets.QLabel(self.fiwalkTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiwalkOutputFileLabel.setFont(font)
        self.fiwalkOutputFileLabel.setObjectName("fiwalkOutputFileLabel")
        self.gridLayout_3.addWidget(self.fiwalkOutputFileLabel, 4, 0, 1, 2)
        self.fiwalkOutputFileToolButton = QtWidgets.QToolButton(self.fiwalkTab)
        self.fiwalkOutputFileToolButton.setObjectName("fiwalkOutputFileToolButton")
        self.gridLayout_3.addWidget(self.fiwalkOutputFileToolButton, 5, 4, 1, 1)
        self.fiwalkFormatCheck = QtWidgets.QCheckBox(self.fiwalkTab)
        self.fiwalkFormatCheck.setChecked(True)
        self.fiwalkFormatCheck.setObjectName("fiwalkFormatCheck")
        self.gridLayout_3.addWidget(self.fiwalkFormatCheck, 6, 0, 1, 2)
        self.fiwalkMD5Check = QtWidgets.QCheckBox(self.fiwalkTab)
        self.fiwalkMD5Check.setChecked(True)
        self.fiwalkMD5Check.setObjectName("fiwalkMD5Check")
        self.gridLayout_3.addWidget(self.fiwalkMD5Check, 7, 0, 1, 2)
        self.fiwalkSHACheck = QtWidgets.QCheckBox(self.fiwalkTab)
        self.fiwalkSHACheck.setObjectName("fiwalkSHACheck")
        self.gridLayout_3.addWidget(self.fiwalkSHACheck, 8, 0, 1, 2)
        self.fiwalkTextEditLabel = QtWidgets.QLabel(self.fiwalkTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiwalkTextEditLabel.setFont(font)
        self.fiwalkTextEditLabel.setObjectName("fiwalkTextEditLabel")
        self.gridLayout_3.addWidget(self.fiwalkTextEditLabel, 9, 0, 1, 1)
        self.fiwalkProgress = QtWidgets.QProgressBar(self.fiwalkTab)
        self.fiwalkProgress.setMaximum(1)
        self.fiwalkProgress.setProperty("value", -1)
        self.fiwalkProgress.setObjectName("fiwalkProgress")
        self.gridLayout_3.addWidget(self.fiwalkProgress, 11, 0, 1, 1)
        self.fiwalkClose = QtWidgets.QPushButton(self.fiwalkTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fiwalkClose.sizePolicy().hasHeightForWidth())
        self.fiwalkClose.setSizePolicy(sizePolicy)
        self.fiwalkClose.setObjectName("fiwalkClose")
        self.gridLayout_3.addWidget(self.fiwalkClose, 11, 1, 1, 1)
        self.fiwalkCancel = QtWidgets.QPushButton(self.fiwalkTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fiwalkCancel.sizePolicy().hasHeightForWidth())
        self.fiwalkCancel.setSizePolicy(sizePolicy)
        self.fiwalkCancel.setObjectName("fiwalkCancel")
        self.gridLayout_3.addWidget(self.fiwalkCancel, 11, 2, 1, 1)
        self.fiwalkRun = QtWidgets.QPushButton(self.fiwalkTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fiwalkRun.sizePolicy().hasHeightForWidth())
        self.fiwalkRun.setSizePolicy(sizePolicy)
        self.fiwalkRun.setObjectName("fiwalkRun")
        self.gridLayout_3.addWidget(self.fiwalkRun, 11, 3, 1, 1)
        self.fiwalkImageFileLineEdit = QtWidgets.QLineEdit(self.fiwalkTab)
        self.fiwalkImageFileLineEdit.setObjectName("fiwalkImageFileLineEdit")
        self.gridLayout_3.addWidget(self.fiwalkImageFileLineEdit, 2, 0, 1, 4)
        self.fiwalkOutputFileLineEdit = QtWidgets.QLineEdit(self.fiwalkTab)
        self.fiwalkOutputFileLineEdit.setObjectName("fiwalkOutputFileLineEdit")
        self.gridLayout_3.addWidget(self.fiwalkOutputFileLineEdit, 5, 0, 1, 4)
        self.fiwalkTextEdit = QtWidgets.QTextEdit(self.fiwalkTab)
        self.fiwalkTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.fiwalkTextEdit.setObjectName("fiwalkTextEdit")
        self.gridLayout_3.addWidget(self.fiwalkTextEdit, 10, 0, 1, 4)
        self.tabWidget.addTab(self.fiwalkTab, "")
        self.fiwalkBatchTab = QtWidgets.QWidget()
        self.fiwalkBatchTab.setObjectName("fiwalkBatchTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.fiwalkBatchTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.fiwalkBatchHeaderLabel = QtWidgets.QLabel(self.fiwalkBatchTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.fiwalkBatchHeaderLabel.setFont(font)
        self.fiwalkBatchHeaderLabel.setWordWrap(True)
        self.fiwalkBatchHeaderLabel.setObjectName("fiwalkBatchHeaderLabel")
        self.gridLayout_5.addWidget(self.fiwalkBatchHeaderLabel, 0, 0, 1, 5)
        self.fiwalkBatchImageLabel = QtWidgets.QLabel(self.fiwalkBatchTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiwalkBatchImageLabel.setFont(font)
        self.fiwalkBatchImageLabel.setObjectName("fiwalkBatchImageLabel")
        self.gridLayout_5.addWidget(self.fiwalkBatchImageLabel, 1, 0, 1, 1)
        self.fiwalkBatchImageToolButton = QtWidgets.QToolButton(self.fiwalkBatchTab)
        self.fiwalkBatchImageToolButton.setObjectName("fiwalkBatchImageToolButton")
        self.gridLayout_5.addWidget(self.fiwalkBatchImageToolButton, 2, 4, 1, 1)
        self.fiwalkBatchCustomDirCheck = QtWidgets.QCheckBox(self.fiwalkBatchTab)
        self.fiwalkBatchCustomDirCheck.setObjectName("fiwalkBatchCustomDirCheck")
        self.gridLayout_5.addWidget(self.fiwalkBatchCustomDirCheck, 3, 0, 1, 1)
        self.fiwalkBatchCustomDirLabel = QtWidgets.QLabel(self.fiwalkBatchTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiwalkBatchCustomDirLabel.setFont(font)
        self.fiwalkBatchCustomDirLabel.setObjectName("fiwalkBatchCustomDirLabel")
        self.gridLayout_5.addWidget(self.fiwalkBatchCustomDirLabel, 4, 0, 1, 2)
        self.fiwalkBatchCustomDirToolButton = QtWidgets.QToolButton(self.fiwalkBatchTab)
        self.fiwalkBatchCustomDirToolButton.setObjectName("fiwalkBatchCustomDirToolButton")
        self.gridLayout_5.addWidget(self.fiwalkBatchCustomDirToolButton, 5, 4, 1, 1)
        self.fiwalkBatchFormatCheck = QtWidgets.QCheckBox(self.fiwalkBatchTab)
        self.fiwalkBatchFormatCheck.setChecked(True)
        self.fiwalkBatchFormatCheck.setObjectName("fiwalkBatchFormatCheck")
        self.gridLayout_5.addWidget(self.fiwalkBatchFormatCheck, 6, 0, 1, 2)
        self.fiwalkBatchMD5Check = QtWidgets.QCheckBox(self.fiwalkBatchTab)
        self.fiwalkBatchMD5Check.setChecked(True)
        self.fiwalkBatchMD5Check.setObjectName("fiwalkBatchMD5Check")
        self.gridLayout_5.addWidget(self.fiwalkBatchMD5Check, 7, 0, 1, 2)
        self.fiwalkBatchSHACheck = QtWidgets.QCheckBox(self.fiwalkBatchTab)
        self.fiwalkBatchSHACheck.setObjectName("fiwalkBatchSHACheck")
        self.gridLayout_5.addWidget(self.fiwalkBatchSHACheck, 8, 0, 1, 2)
        self.fiwalkBatchTextEditLabel = QtWidgets.QLabel(self.fiwalkBatchTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiwalkBatchTextEditLabel.setFont(font)
        self.fiwalkBatchTextEditLabel.setObjectName("fiwalkBatchTextEditLabel")
        self.gridLayout_5.addWidget(self.fiwalkBatchTextEditLabel, 9, 0, 1, 1)
        self.fiwalkBatchProgress = QtWidgets.QProgressBar(self.fiwalkBatchTab)
        self.fiwalkBatchProgress.setMaximum(1)
        self.fiwalkBatchProgress.setProperty("value", -1)
        self.fiwalkBatchProgress.setObjectName("fiwalkBatchProgress")
        self.gridLayout_5.addWidget(self.fiwalkBatchProgress, 11, 0, 1, 1)
        self.fiwalkBatchClose = QtWidgets.QPushButton(self.fiwalkBatchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fiwalkBatchClose.sizePolicy().hasHeightForWidth())
        self.fiwalkBatchClose.setSizePolicy(sizePolicy)
        self.fiwalkBatchClose.setObjectName("fiwalkBatchClose")
        self.gridLayout_5.addWidget(self.fiwalkBatchClose, 11, 1, 1, 1)
        self.fiwalkBatchCancel = QtWidgets.QPushButton(self.fiwalkBatchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fiwalkBatchCancel.sizePolicy().hasHeightForWidth())
        self.fiwalkBatchCancel.setSizePolicy(sizePolicy)
        self.fiwalkBatchCancel.setObjectName("fiwalkBatchCancel")
        self.gridLayout_5.addWidget(self.fiwalkBatchCancel, 11, 2, 1, 1)
        self.fiwalkBatchRun = QtWidgets.QPushButton(self.fiwalkBatchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fiwalkBatchRun.sizePolicy().hasHeightForWidth())
        self.fiwalkBatchRun.setSizePolicy(sizePolicy)
        self.fiwalkBatchRun.setObjectName("fiwalkBatchRun")
        self.gridLayout_5.addWidget(self.fiwalkBatchRun, 11, 3, 1, 1)
        self.fiwalkBatchTextEdit = QtWidgets.QTextEdit(self.fiwalkBatchTab)
        self.fiwalkBatchTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.fiwalkBatchTextEdit.setObjectName("fiwalkBatchTextEdit")
        self.gridLayout_5.addWidget(self.fiwalkBatchTextEdit, 10, 0, 1, 4)
        self.fiwalkBatchCustomDirLineEdit = QtWidgets.QLineEdit(self.fiwalkBatchTab)
        self.fiwalkBatchCustomDirLineEdit.setObjectName("fiwalkBatchCustomDirLineEdit")
        self.gridLayout_5.addWidget(self.fiwalkBatchCustomDirLineEdit, 5, 0, 1, 4)
        self.fiwalkBatchImageLineEdit = QtWidgets.QLineEdit(self.fiwalkBatchTab)
        self.fiwalkBatchImageLineEdit.setText("")
        self.fiwalkBatchImageLineEdit.setObjectName("fiwalkBatchImageLineEdit")
        self.gridLayout_5.addWidget(self.fiwalkBatchImageLineEdit, 2, 0, 1, 4)
        self.tabWidget.addTab(self.fiwalkBatchTab, "")
        self.annTab = QtWidgets.QWidget()
        self.annTab.setObjectName("annTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.annTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.annHeaderLabel = QtWidgets.QLabel(self.annTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.annHeaderLabel.setFont(font)
        self.annHeaderLabel.setWordWrap(True)
        self.annHeaderLabel.setObjectName("annHeaderLabel")
        self.gridLayout_4.addWidget(self.annHeaderLabel, 0, 0, 1, 5)
        self.annImageLabel = QtWidgets.QLabel(self.annTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annImageLabel.setFont(font)
        self.annImageLabel.setObjectName("annImageLabel")
        self.gridLayout_4.addWidget(self.annImageLabel, 1, 0, 1, 1)
        self.annImageToolButton = QtWidgets.QToolButton(self.annTab)
        self.annImageToolButton.setObjectName("annImageToolButton")
        self.gridLayout_4.addWidget(self.annImageToolButton, 2, 4, 1, 1)
        self.annBEFeatureLabel = QtWidgets.QLabel(self.annTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annBEFeatureLabel.setFont(font)
        self.annBEFeatureLabel.setObjectName("annBEFeatureLabel")
        self.gridLayout_4.addWidget(self.annBEFeatureLabel, 3, 0, 1, 1)
        self.annBEFeatureToolButton = QtWidgets.QToolButton(self.annTab)
        self.annBEFeatureToolButton.setObjectName("annBEFeatureToolButton")
        self.gridLayout_4.addWidget(self.annBEFeatureToolButton, 4, 4, 1, 1)
        self.annOutDirLabel = QtWidgets.QLabel(self.annTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annOutDirLabel.setFont(font)
        self.annOutDirLabel.setObjectName("annOutDirLabel")
        self.gridLayout_4.addWidget(self.annOutDirLabel, 5, 0, 1, 1)
        self.annOutDirToolButton = QtWidgets.QToolButton(self.annTab)
        self.annOutDirToolButton.setObjectName("annOutDirToolButton")
        self.gridLayout_4.addWidget(self.annOutDirToolButton, 6, 4, 1, 1)
        self.annBEPyDirLabel = QtWidgets.QLabel(self.annTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annBEPyDirLabel.setFont(font)
        self.annBEPyDirLabel.setObjectName("annBEPyDirLabel")
        self.gridLayout_4.addWidget(self.annBEPyDirLabel, 7, 0, 1, 1)
        self.annBEPyDirToolButton = QtWidgets.QToolButton(self.annTab)
        self.annBEPyDirToolButton.setObjectName("annBEPyDirToolButton")
        self.gridLayout_4.addWidget(self.annBEPyDirToolButton, 8, 4, 1, 1)
        self.annBETextEditLabel = QtWidgets.QLabel(self.annTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annBETextEditLabel.setFont(font)
        self.annBETextEditLabel.setObjectName("annBETextEditLabel")
        self.gridLayout_4.addWidget(self.annBETextEditLabel, 9, 0, 1, 1)
        self.annProgress = QtWidgets.QProgressBar(self.annTab)
        self.annProgress.setMaximum(1)
        self.annProgress.setProperty("value", -1)
        self.annProgress.setObjectName("annProgress")
        self.gridLayout_4.addWidget(self.annProgress, 11, 0, 1, 1)
        self.annClose = QtWidgets.QPushButton(self.annTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.annClose.sizePolicy().hasHeightForWidth())
        self.annClose.setSizePolicy(sizePolicy)
        self.annClose.setObjectName("annClose")
        self.gridLayout_4.addWidget(self.annClose, 11, 1, 1, 1)
        self.annCancel = QtWidgets.QPushButton(self.annTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.annCancel.sizePolicy().hasHeightForWidth())
        self.annCancel.setSizePolicy(sizePolicy)
        self.annCancel.setObjectName("annCancel")
        self.gridLayout_4.addWidget(self.annCancel, 11, 2, 1, 1)
        self.annRun = QtWidgets.QPushButton(self.annTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.annRun.sizePolicy().hasHeightForWidth())
        self.annRun.setSizePolicy(sizePolicy)
        self.annRun.setObjectName("annRun")
        self.gridLayout_4.addWidget(self.annRun, 11, 3, 1, 1)
        self.annBETextEdit = QtWidgets.QTextEdit(self.annTab)
        self.annBETextEdit.setAutoFillBackground(True)
        self.annBETextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.annBETextEdit.setObjectName("annBETextEdit")
        self.gridLayout_4.addWidget(self.annBETextEdit, 10, 0, 1, 4)
        self.annBEPyDirLineEdit = QtWidgets.QLineEdit(self.annTab)
        self.annBEPyDirLineEdit.setText("")
        self.annBEPyDirLineEdit.setObjectName("annBEPyDirLineEdit")
        self.gridLayout_4.addWidget(self.annBEPyDirLineEdit, 8, 0, 1, 4)
        self.annOutDirLineEdit = QtWidgets.QLineEdit(self.annTab)
        self.annOutDirLineEdit.setObjectName("annOutDirLineEdit")
        self.gridLayout_4.addWidget(self.annOutDirLineEdit, 6, 0, 1, 4)
        self.annBEFeatureLineEdit = QtWidgets.QLineEdit(self.annTab)
        self.annBEFeatureLineEdit.setText("")
        self.annBEFeatureLineEdit.setObjectName("annBEFeatureLineEdit")
        self.gridLayout_4.addWidget(self.annBEFeatureLineEdit, 4, 0, 1, 4)
        self.annImageLineEdit = QtWidgets.QLineEdit(self.annTab)
        self.annImageLineEdit.setText("")
        self.annImageLineEdit.setObjectName("annImageLineEdit")
        self.gridLayout_4.addWidget(self.annImageLineEdit, 2, 0, 1, 4)
        self.tabWidget.addTab(self.annTab, "")
        self.reportsTab = QtWidgets.QWidget()
        self.reportsTab.setObjectName("reportsTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.reportsTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.reportsHeaderLabel = QtWidgets.QLabel(self.reportsTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.reportsHeaderLabel.setFont(font)
        self.reportsHeaderLabel.setWordWrap(True)
        self.reportsHeaderLabel.setObjectName("reportsHeaderLabel")
        self.gridLayout_2.addWidget(self.reportsHeaderLabel, 0, 0, 1, 5)
        self.reportsFiwalkLabel = QtWidgets.QLabel(self.reportsTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reportsFiwalkLabel.setFont(font)
        self.reportsFiwalkLabel.setObjectName("reportsFiwalkLabel")
        self.gridLayout_2.addWidget(self.reportsFiwalkLabel, 1, 0, 1, 1)
        self.reportsFiwalkToolButton = QtWidgets.QToolButton(self.reportsTab)
        self.reportsFiwalkToolButton.setObjectName("reportsFiwalkToolButton")
        self.gridLayout_2.addWidget(self.reportsFiwalkToolButton, 2, 4, 1, 1)
        self.reportsAnnDirLabel = QtWidgets.QLabel(self.reportsTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reportsAnnDirLabel.setFont(font)
        self.reportsAnnDirLabel.setObjectName("reportsAnnDirLabel")
        self.gridLayout_2.addWidget(self.reportsAnnDirLabel, 3, 0, 1, 1)
        self.reportsAnnDirToolButton = QtWidgets.QToolButton(self.reportsTab)
        self.reportsAnnDirToolButton.setObjectName("reportsAnnDirToolButton")
        self.gridLayout_2.addWidget(self.reportsAnnDirToolButton, 4, 4, 1, 1)
        self.reportsOutDirLabel = QtWidgets.QLabel(self.reportsTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reportsOutDirLabel.setFont(font)
        self.reportsOutDirLabel.setObjectName("reportsOutDirLabel")
        self.gridLayout_2.addWidget(self.reportsOutDirLabel, 5, 0, 1, 1)
        self.reportsOutDirToolButton = QtWidgets.QToolButton(self.reportsTab)
        self.reportsOutDirToolButton.setObjectName("reportsOutDirToolButton")
        self.gridLayout_2.addWidget(self.reportsOutDirToolButton, 6, 4, 1, 1)
        self.reportsConfigLabel = QtWidgets.QLabel(self.reportsTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reportsConfigLabel.setFont(font)
        self.reportsConfigLabel.setObjectName("reportsConfigLabel")
        self.gridLayout_2.addWidget(self.reportsConfigLabel, 7, 0, 1, 1)
        self.reportsCOnfigFileToolButton = QtWidgets.QToolButton(self.reportsTab)
        self.reportsCOnfigFileToolButton.setObjectName("reportsCOnfigFileToolButton")
        self.gridLayout_2.addWidget(self.reportsCOnfigFileToolButton, 8, 4, 1, 1)
        self.reportsTextEditLabel = QtWidgets.QLabel(self.reportsTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reportsTextEditLabel.setFont(font)
        self.reportsTextEditLabel.setObjectName("reportsTextEditLabel")
        self.gridLayout_2.addWidget(self.reportsTextEditLabel, 9, 0, 1, 1)
        self.reportsProgress = QtWidgets.QProgressBar(self.reportsTab)
        self.reportsProgress.setMaximum(1)
        self.reportsProgress.setProperty("value", -1)
        self.reportsProgress.setObjectName("reportsProgress")
        self.gridLayout_2.addWidget(self.reportsProgress, 11, 0, 1, 1)
        self.reportsClose = QtWidgets.QPushButton(self.reportsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportsClose.sizePolicy().hasHeightForWidth())
        self.reportsClose.setSizePolicy(sizePolicy)
        self.reportsClose.setObjectName("reportsClose")
        self.gridLayout_2.addWidget(self.reportsClose, 11, 1, 1, 1)
        self.reportsCancel = QtWidgets.QPushButton(self.reportsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportsCancel.sizePolicy().hasHeightForWidth())
        self.reportsCancel.setSizePolicy(sizePolicy)
        self.reportsCancel.setObjectName("reportsCancel")
        self.gridLayout_2.addWidget(self.reportsCancel, 11, 2, 1, 1)
        self.reportsRun = QtWidgets.QPushButton(self.reportsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportsRun.sizePolicy().hasHeightForWidth())
        self.reportsRun.setSizePolicy(sizePolicy)
        self.reportsRun.setObjectName("reportsRun")
        self.gridLayout_2.addWidget(self.reportsRun, 11, 3, 1, 1)
        self.reportsTextEdit = QtWidgets.QTextEdit(self.reportsTab)
        self.reportsTextEdit.setAutoFillBackground(True)
        self.reportsTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.reportsTextEdit.setObjectName("reportsTextEdit")
        self.gridLayout_2.addWidget(self.reportsTextEdit, 10, 0, 1, 4)
        self.reportsConfigLineEdit = QtWidgets.QLineEdit(self.reportsTab)
        self.reportsConfigLineEdit.setObjectName("reportsConfigLineEdit")
        self.gridLayout_2.addWidget(self.reportsConfigLineEdit, 8, 0, 1, 4)
        self.reportsOutDirLineEdit = QtWidgets.QLineEdit(self.reportsTab)
        self.reportsOutDirLineEdit.setObjectName("reportsOutDirLineEdit")
        self.gridLayout_2.addWidget(self.reportsOutDirLineEdit, 6, 0, 1, 4)
        self.reportsAnnDirLineEdit = QtWidgets.QLineEdit(self.reportsTab)
        self.reportsAnnDirLineEdit.setText("")
        self.reportsAnnDirLineEdit.setObjectName("reportsAnnDirLineEdit")
        self.gridLayout_2.addWidget(self.reportsAnnDirLineEdit, 4, 0, 1, 4)
        self.reportsFiwalkLineEdit = QtWidgets.QLineEdit(self.reportsTab)
        self.reportsFiwalkLineEdit.setText("")
        self.reportsFiwalkLineEdit.setObjectName("reportsFiwalkLineEdit")
        self.gridLayout_2.addWidget(self.reportsFiwalkLineEdit, 2, 0, 1, 4)
        self.tabWidget.addTab(self.reportsTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionShow_Help = QtWidgets.QAction(MainWindow)
        self.actionShow_Help.setObjectName("actionShow_Help")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuHelp.addAction(self.actionShow_Help)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.fiwalkImageFileLineEdit, self.fiwalkImageFileToolButton)
        MainWindow.setTabOrder(self.fiwalkImageFileToolButton, self.fiwalkOutputFileLineEdit)
        MainWindow.setTabOrder(self.fiwalkOutputFileLineEdit, self.fiwalkOutputFileToolButton)
        MainWindow.setTabOrder(self.fiwalkOutputFileToolButton, self.fiwalkTextEdit)
        MainWindow.setTabOrder(self.fiwalkTextEdit, self.fiwalkClose)
        MainWindow.setTabOrder(self.fiwalkClose, self.fiwalkCancel)
        MainWindow.setTabOrder(self.fiwalkCancel, self.fiwalkRun)
        MainWindow.setTabOrder(self.fiwalkRun, self.annImageLineEdit)
        MainWindow.setTabOrder(self.annImageLineEdit, self.annImageToolButton)
        MainWindow.setTabOrder(self.annImageToolButton, self.annBEFeatureLineEdit)
        MainWindow.setTabOrder(self.annBEFeatureLineEdit, self.annBEFeatureToolButton)
        MainWindow.setTabOrder(self.annBEFeatureToolButton, self.annOutDirLineEdit)
        MainWindow.setTabOrder(self.annOutDirLineEdit, self.annOutDirToolButton)
        MainWindow.setTabOrder(self.annOutDirToolButton, self.annBEPyDirLineEdit)
        MainWindow.setTabOrder(self.annBEPyDirLineEdit, self.annBEPyDirToolButton)
        MainWindow.setTabOrder(self.annBEPyDirToolButton, self.annBETextEdit)
        MainWindow.setTabOrder(self.annBETextEdit, self.annClose)
        MainWindow.setTabOrder(self.annClose, self.annCancel)
        MainWindow.setTabOrder(self.annCancel, self.annRun)
        MainWindow.setTabOrder(self.annRun, self.reportsFiwalkLineEdit)
        MainWindow.setTabOrder(self.reportsFiwalkLineEdit, self.reportsFiwalkToolButton)
        MainWindow.setTabOrder(self.reportsFiwalkToolButton, self.reportsAnnDirLineEdit)
        MainWindow.setTabOrder(self.reportsAnnDirLineEdit, self.reportsAnnDirToolButton)
        MainWindow.setTabOrder(self.reportsAnnDirToolButton, self.reportsOutDirLineEdit)
        MainWindow.setTabOrder(self.reportsOutDirLineEdit, self.reportsOutDirToolButton)
        MainWindow.setTabOrder(self.reportsOutDirToolButton, self.reportsConfigLineEdit)
        MainWindow.setTabOrder(self.reportsConfigLineEdit, self.reportsCOnfigFileToolButton)
        MainWindow.setTabOrder(self.reportsCOnfigFileToolButton, self.reportsTextEdit)
        MainWindow.setTabOrder(self.reportsTextEdit, self.reportsClose)
        MainWindow.setTabOrder(self.reportsClose, self.reportsCancel)
        MainWindow.setTabOrder(self.reportsCancel, self.reportsRun)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BitCurator Reporting Tool"))
        self.runAllHeaderLabel.setText(_translate("MainWindow", "Run fiwalk, annotate the bulk_extractor output, and generate Office / PDF reports."))
        self.runAllBEViewerButton.setText(_translate("MainWindow", "Launch BEViewer"))
        self.runAllImageFileLabel.setText(_translate("MainWindow", "Image File"))
        self.runAllImageFileToolButton.setText(_translate("MainWindow", "..."))
        self.runAllBEDirectoryToolButton.setText(_translate("MainWindow", "..."))
        self.runAllOutputDirToolButton.setText(_translate("MainWindow", "..."))
        self.runAllConfigToolButton.setText(_translate("MainWindow", "..."))
        self.runAllTextEditLabel.setText(_translate("MainWindow", "Command Line Output"))
        self.runAllClose.setText(_translate("MainWindow", "Close"))
        self.runAllCancel.setText(_translate("MainWindow", "Cancel"))
        self.runAllRun.setText(_translate("MainWindow", "Run"))
        self.runAllConfigLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File"))
        self.runAllLineEditLabel.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory"))
        self.runAllBEDirectoryLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory"))
        self.runAllImageFileLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File"))
        self.runAllBEDirectoryLabel.setText(_translate("MainWindow", "Bulk Extractor Feature Directory"))
        self.runAllOutputDirLabel.setText(_translate("MainWindow", "Output Directory (fiwalk output, annotated features, and reports will appear in here)"))
        self.runaAllBEDescriptorLabel.setText(_translate("MainWindow", "If you haven\'t run bulk_extractor yet, use the button to the right to launch and run it first."))
        self.runAllConfigLabel.setText(_translate("MainWindow", "Config File (Optional)"))
        self.runAllDisableFiwalkXLSXCheck.setText(_translate("MainWindow", "Disable fiwalk XLSX report (reduces runtime; DFXML will still be created)"))
        self.runAllDisableAnnotatedXLSXCheck.setText(_translate("MainWindow", "Disable annotated features XLSX reports (reduces runtime)"))
        self.runAllDisablePDFCheck.setText(_translate("MainWindow", "Disable PDF reports (reduces runtime)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.runAllTab), _translate("MainWindow", "Run All"))
        self.runAllAutoHeaderLabel.setText(_translate("MainWindow", "Run fiwalk, annotate the bulk_extractor output, and generate Office / PDF reports."))
        self.runAllAutoDescriptorLabel.setText(_translate("MainWindow", "All tools, including bulk_extractor, will be run automatically with their default settings. By default, all reports will be placed in a new directory named [IMAGE_NAME]-reports in the directory in which the image is located. You may choose a different output directory using the option below."))
        self.runAllAutoImageFileLabel.setText(_translate("MainWindow", "Image File"))
        self.runAllAutoImageFileToolButton.setText(_translate("MainWindow", "..."))
        self.runAllAutoOutputDirCheckBox.setText(_translate("MainWindow", "Use Custom Output Directory"))
        self.runAllAutoOutputDirLabel.setText(_translate("MainWindow", "Custom Output Directory (ignored unless checkbox is selected)"))
        self.runAllAutoOutputDirToolButton.setText(_translate("MainWindow", "..."))
        self.runAllAutoDisableFiwalkXLSXCheck.setText(_translate("MainWindow", "Disable fiwalk XLSX report (DFXML will still be created)"))
        self.runAllAutoDisableAnnotatedXLSXCheck.setText(_translate("MainWindow", "Disable annotated features XLSX reports"))
        self.runAllAutoDisablePDFCheck.setText(_translate("MainWindow", "Disable PDF reports"))
        self.runAllAutoTextEditLabel.setText(_translate("MainWindow", "Command Line Output"))
        self.runAllAutoClose.setText(_translate("MainWindow", "Close"))
        self.runAllAutoCancel.setText(_translate("MainWindow", "Cancel"))
        self.runAllAutoRun.setText(_translate("MainWindow", "Run"))
        self.runAllAutoImageFileLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File"))
        self.runAllAutoOutputDirLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.runAllAutoTab), _translate("MainWindow", "Run All (Auto)"))
        self.fiwalkHeaderLabel.setText(_translate("MainWindow", "Fiwalk produces a DFXML file showing the volumes, directories, and files contained within a disk image. Output is an XML file named [IMAGE_NAME].xml in the same directory unless otherwise specified."))
        self.fiwalkImageFileLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Image File</span></p></body></html>"))
        self.fiwalkImageFileToolButton.setText(_translate("MainWindow", "..."))
        self.fiwalkOutputFileCheckBox.setText(_translate("MainWindow", "Use Custom DFXML File Name"))
        self.fiwalkOutputFileLabel.setText(_translate("MainWindow", "Custom DFXML File Name (ignored unless checkbox is selected!)"))
        self.fiwalkOutputFileToolButton.setText(_translate("MainWindow", "..."))
        self.fiwalkFormatCheck.setText(_translate("MainWindow", "Enable format identification using \'file\' (increases runtime)"))
        self.fiwalkMD5Check.setText(_translate("MainWindow", "Enable MD5 checksums in output (increases runtime)"))
        self.fiwalkSHACheck.setText(_translate("MainWindow", "Enable SHA256 checksums in output (increases runtime)"))
        self.fiwalkTextEditLabel.setText(_translate("MainWindow", "Command line output:"))
        self.fiwalkClose.setText(_translate("MainWindow", "Close"))
        self.fiwalkCancel.setText(_translate("MainWindow", "Cancel"))
        self.fiwalkRun.setText(_translate("MainWindow", "Run"))
        self.fiwalkImageFileLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File"))
        self.fiwalkOutputFileLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fiwalkTab), _translate("MainWindow", "Fiwalk"))
        self.fiwalkBatchHeaderLabel.setText(_translate("MainWindow", "Fiwalk produces a DFXML file showing the volumes, directories, and files contained within a disk image. In this tab, you can point fiwalk at a directory containing one or more E01, AFF, or raw disk images. Output files will be named [IMAGE_NAME].xml"))
        self.fiwalkBatchImageLabel.setText(_translate("MainWindow", "<html><head/><body><p>Directory Containing Image Files</p></body></html>"))
        self.fiwalkBatchImageToolButton.setText(_translate("MainWindow", "..."))
        self.fiwalkBatchCustomDirCheck.setText(_translate("MainWindow", "Use Custom Output Directory"))
        self.fiwalkBatchCustomDirLabel.setText(_translate("MainWindow", "Custom Output Directory (ignored unless checkbox is selected!)"))
        self.fiwalkBatchCustomDirToolButton.setText(_translate("MainWindow", "..."))
        self.fiwalkBatchFormatCheck.setText(_translate("MainWindow", "Enable format identification using \'file\' (increases runtime)"))
        self.fiwalkBatchMD5Check.setText(_translate("MainWindow", "Enable MD5 checksums in output (increases runtime)"))
        self.fiwalkBatchSHACheck.setText(_translate("MainWindow", "Enable SHA256 checksums in output (increases runtime)"))
        self.fiwalkBatchTextEditLabel.setText(_translate("MainWindow", "Command line output:"))
        self.fiwalkBatchClose.setText(_translate("MainWindow", "Close"))
        self.fiwalkBatchCancel.setText(_translate("MainWindow", "Cancel"))
        self.fiwalkBatchRun.setText(_translate("MainWindow", "Run"))
        self.fiwalkBatchCustomDirLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory"))
        self.fiwalkBatchImageLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fiwalkBatchTab), _translate("MainWindow", "Fiwalk (Batch)"))
        self.annHeaderLabel.setText(_translate("MainWindow", "Produces reports that identify which bulk_extractor features are contained within files in a disk image"))
        self.annImageLabel.setText(_translate("MainWindow", "Image File"))
        self.annImageToolButton.setText(_translate("MainWindow", "..."))
        self.annBEFeatureLabel.setText(_translate("MainWindow", "Bulk Extractor Feature Directory"))
        self.annBEFeatureToolButton.setText(_translate("MainWindow", "..."))
        self.annOutDirLabel.setText(_translate("MainWindow", "Annotated Feature Files Directory (new)"))
        self.annOutDirToolButton.setText(_translate("MainWindow", "..."))
        self.annBEPyDirLabel.setText(_translate("MainWindow", "Bulk Extractor Python Directory (optional)"))
        self.annBEPyDirToolButton.setText(_translate("MainWindow", "..."))
        self.annBETextEditLabel.setText(_translate("MainWindow", "Command Line Output"))
        self.annClose.setText(_translate("MainWindow", "Close"))
        self.annCancel.setText(_translate("MainWindow", "Cancel"))
        self.annRun.setText(_translate("MainWindow", "Run"))
        self.annBEPyDirLineEdit.setPlaceholderText(_translate("MainWindow", "/home/bcadmin/Tools/bulk_extractor/python"))
        self.annOutDirLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory"))
        self.annBEFeatureLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory"))
        self.annImageLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.annTab), _translate("MainWindow", "Annotate BE Reports"))
        self.reportsHeaderLabel.setText(_translate("MainWindow", "Produces Office Open XML and PDF Reports. Use only if you have already run fiwalk and bulk_extractor."))
        self.reportsFiwalkLabel.setText(_translate("MainWindow", "Fiwalk XML File"))
        self.reportsFiwalkToolButton.setText(_translate("MainWindow", "..."))
        self.reportsAnnDirLabel.setText(_translate("MainWindow", "Annotated Feature Files Directory"))
        self.reportsAnnDirToolButton.setText(_translate("MainWindow", "..."))
        self.reportsOutDirLabel.setText(_translate("MainWindow", "Output Directory for Reports"))
        self.reportsOutDirToolButton.setText(_translate("MainWindow", "..."))
        self.reportsConfigLabel.setText(_translate("MainWindow", "Config File (Optional)"))
        self.reportsCOnfigFileToolButton.setText(_translate("MainWindow", "..."))
        self.reportsTextEditLabel.setText(_translate("MainWindow", "Command Line Output"))
        self.reportsClose.setText(_translate("MainWindow", "Close"))
        self.reportsCancel.setText(_translate("MainWindow", "Cancel"))
        self.reportsRun.setText(_translate("MainWindow", "Run"))
        self.reportsConfigLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File"))
        self.reportsOutDirLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory"))
        self.reportsAnnDirLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory"))
        self.reportsFiwalkLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reportsTab), _translate("MainWindow", "Reports"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionShow_Help.setText(_translate("MainWindow", "Show Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

