# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIv11-Jan31-2016.ui'
#
# Created: Mon Feb  1 20:47:42 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(670, 753)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.runAllTab = QtGui.QWidget()
        self.runAllTab.setObjectName(_fromUtf8("runAllTab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.runAllTab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.runAllHeaderLabel = QtGui.QLabel(self.runAllTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.runAllHeaderLabel.setFont(font)
        self.runAllHeaderLabel.setWordWrap(True)
        self.runAllHeaderLabel.setObjectName(_fromUtf8("runAllHeaderLabel"))
        self.gridLayout_7.addWidget(self.runAllHeaderLabel, 0, 0, 1, 6)
        self.runAllBEViewerButton = QtGui.QPushButton(self.runAllTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAllBEViewerButton.sizePolicy().hasHeightForWidth())
        self.runAllBEViewerButton.setSizePolicy(sizePolicy)
        self.runAllBEViewerButton.setObjectName(_fromUtf8("runAllBEViewerButton"))
        self.gridLayout_7.addWidget(self.runAllBEViewerButton, 1, 3, 1, 2)
        self.runAllImageFileLabel = QtGui.QLabel(self.runAllTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllImageFileLabel.setFont(font)
        self.runAllImageFileLabel.setObjectName(_fromUtf8("runAllImageFileLabel"))
        self.gridLayout_7.addWidget(self.runAllImageFileLabel, 2, 0, 1, 1)
        self.runAllImageFileToolButton = QtGui.QToolButton(self.runAllTab)
        self.runAllImageFileToolButton.setObjectName(_fromUtf8("runAllImageFileToolButton"))
        self.gridLayout_7.addWidget(self.runAllImageFileToolButton, 3, 5, 1, 1)
        self.runAllBEDirectoryToolButton = QtGui.QToolButton(self.runAllTab)
        self.runAllBEDirectoryToolButton.setObjectName(_fromUtf8("runAllBEDirectoryToolButton"))
        self.gridLayout_7.addWidget(self.runAllBEDirectoryToolButton, 5, 5, 1, 1)
        self.runAllOutputDirToolButton = QtGui.QToolButton(self.runAllTab)
        self.runAllOutputDirToolButton.setObjectName(_fromUtf8("runAllOutputDirToolButton"))
        self.gridLayout_7.addWidget(self.runAllOutputDirToolButton, 7, 5, 1, 1)
        self.runAllConfigToolButton = QtGui.QToolButton(self.runAllTab)
        self.runAllConfigToolButton.setObjectName(_fromUtf8("runAllConfigToolButton"))
        self.gridLayout_7.addWidget(self.runAllConfigToolButton, 9, 5, 1, 1)
        self.runAllTextEditLabel = QtGui.QLabel(self.runAllTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllTextEditLabel.setFont(font)
        self.runAllTextEditLabel.setObjectName(_fromUtf8("runAllTextEditLabel"))
        self.gridLayout_7.addWidget(self.runAllTextEditLabel, 13, 0, 1, 1)
        self.runAllProgress = QtGui.QProgressBar(self.runAllTab)
        self.runAllProgress.setMaximum(1)
        self.runAllProgress.setProperty("value", -1)
        self.runAllProgress.setObjectName(_fromUtf8("runAllProgress"))
        self.gridLayout_7.addWidget(self.runAllProgress, 15, 0, 1, 1)
        self.runAllClose = QtGui.QPushButton(self.runAllTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAllClose.sizePolicy().hasHeightForWidth())
        self.runAllClose.setSizePolicy(sizePolicy)
        self.runAllClose.setObjectName(_fromUtf8("runAllClose"))
        self.gridLayout_7.addWidget(self.runAllClose, 15, 1, 1, 1)
        self.runAllCancel = QtGui.QPushButton(self.runAllTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAllCancel.sizePolicy().hasHeightForWidth())
        self.runAllCancel.setSizePolicy(sizePolicy)
        self.runAllCancel.setObjectName(_fromUtf8("runAllCancel"))
        self.gridLayout_7.addWidget(self.runAllCancel, 15, 2, 1, 2)
        self.runAllRun = QtGui.QPushButton(self.runAllTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAllRun.sizePolicy().hasHeightForWidth())
        self.runAllRun.setSizePolicy(sizePolicy)
        self.runAllRun.setObjectName(_fromUtf8("runAllRun"))
        self.gridLayout_7.addWidget(self.runAllRun, 15, 4, 1, 1)
        self.runAllTextEdit = QtGui.QTextEdit(self.runAllTab)
        self.runAllTextEdit.setAutoFillBackground(True)
        self.runAllTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.runAllTextEdit.setObjectName(_fromUtf8("runAllTextEdit"))
        self.gridLayout_7.addWidget(self.runAllTextEdit, 14, 0, 1, 5)
        self.runAllConfigLineEdit = QtGui.QLineEdit(self.runAllTab)
        self.runAllConfigLineEdit.setObjectName(_fromUtf8("runAllConfigLineEdit"))
        self.gridLayout_7.addWidget(self.runAllConfigLineEdit, 9, 0, 1, 5)
        self.runAllLineEditLabel = QtGui.QLineEdit(self.runAllTab)
        self.runAllLineEditLabel.setObjectName(_fromUtf8("runAllLineEditLabel"))
        self.gridLayout_7.addWidget(self.runAllLineEditLabel, 7, 0, 1, 5)
        self.runAllBEDirectoryLineEdit = QtGui.QLineEdit(self.runAllTab)
        self.runAllBEDirectoryLineEdit.setObjectName(_fromUtf8("runAllBEDirectoryLineEdit"))
        self.gridLayout_7.addWidget(self.runAllBEDirectoryLineEdit, 5, 0, 1, 5)
        self.runAllImageFileLineEdit = QtGui.QLineEdit(self.runAllTab)
        self.runAllImageFileLineEdit.setText(_fromUtf8(""))
        self.runAllImageFileLineEdit.setMaxLength(0)
        self.runAllImageFileLineEdit.setObjectName(_fromUtf8("runAllImageFileLineEdit"))
        self.gridLayout_7.addWidget(self.runAllImageFileLineEdit, 3, 0, 1, 5)
        self.runAllBEDirectoryLabel = QtGui.QLabel(self.runAllTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllBEDirectoryLabel.setFont(font)
        self.runAllBEDirectoryLabel.setObjectName(_fromUtf8("runAllBEDirectoryLabel"))
        self.gridLayout_7.addWidget(self.runAllBEDirectoryLabel, 4, 0, 1, 5)
        self.runAllOutputDirLabel = QtGui.QLabel(self.runAllTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllOutputDirLabel.setFont(font)
        self.runAllOutputDirLabel.setObjectName(_fromUtf8("runAllOutputDirLabel"))
        self.gridLayout_7.addWidget(self.runAllOutputDirLabel, 6, 0, 1, 5)
        self.runaAllBEDescriptorLabel = QtGui.QLabel(self.runAllTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.runaAllBEDescriptorLabel.setFont(font)
        self.runaAllBEDescriptorLabel.setWordWrap(True)
        self.runaAllBEDescriptorLabel.setObjectName(_fromUtf8("runaAllBEDescriptorLabel"))
        self.gridLayout_7.addWidget(self.runaAllBEDescriptorLabel, 1, 0, 1, 2)
        self.runAllConfigLabel = QtGui.QLabel(self.runAllTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllConfigLabel.setFont(font)
        self.runAllConfigLabel.setObjectName(_fromUtf8("runAllConfigLabel"))
        self.gridLayout_7.addWidget(self.runAllConfigLabel, 8, 0, 1, 5)
        self.runAllDisableFiwalkXLSXCheck = QtGui.QCheckBox(self.runAllTab)
        self.runAllDisableFiwalkXLSXCheck.setObjectName(_fromUtf8("runAllDisableFiwalkXLSXCheck"))
        self.gridLayout_7.addWidget(self.runAllDisableFiwalkXLSXCheck, 10, 0, 1, 5)
        self.runAllDisableAnnotatedXLSXCheck = QtGui.QCheckBox(self.runAllTab)
        self.runAllDisableAnnotatedXLSXCheck.setObjectName(_fromUtf8("runAllDisableAnnotatedXLSXCheck"))
        self.gridLayout_7.addWidget(self.runAllDisableAnnotatedXLSXCheck, 11, 0, 1, 5)
        self.runAllDisablePDFCheck = QtGui.QCheckBox(self.runAllTab)
        self.runAllDisablePDFCheck.setObjectName(_fromUtf8("runAllDisablePDFCheck"))
        self.gridLayout_7.addWidget(self.runAllDisablePDFCheck, 12, 0, 1, 5)
        self.tabWidget.addTab(self.runAllTab, _fromUtf8(""))
        self.runAllAutoTab = QtGui.QWidget()
        self.runAllAutoTab.setObjectName(_fromUtf8("runAllAutoTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.runAllAutoTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.runAllAutoHeaderLabel = QtGui.QLabel(self.runAllAutoTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.runAllAutoHeaderLabel.setFont(font)
        self.runAllAutoHeaderLabel.setWordWrap(True)
        self.runAllAutoHeaderLabel.setObjectName(_fromUtf8("runAllAutoHeaderLabel"))
        self.gridLayout_6.addWidget(self.runAllAutoHeaderLabel, 0, 0, 1, 5)
        self.runAllAutoDescriptorLabel = QtGui.QLabel(self.runAllAutoTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.runAllAutoDescriptorLabel.setFont(font)
        self.runAllAutoDescriptorLabel.setWordWrap(True)
        self.runAllAutoDescriptorLabel.setObjectName(_fromUtf8("runAllAutoDescriptorLabel"))
        self.gridLayout_6.addWidget(self.runAllAutoDescriptorLabel, 1, 0, 1, 4)
        self.runAllAutoImageFileLabel = QtGui.QLabel(self.runAllAutoTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllAutoImageFileLabel.setFont(font)
        self.runAllAutoImageFileLabel.setObjectName(_fromUtf8("runAllAutoImageFileLabel"))
        self.gridLayout_6.addWidget(self.runAllAutoImageFileLabel, 2, 0, 1, 1)
        self.runAllAutoImageFileToolButton = QtGui.QToolButton(self.runAllAutoTab)
        self.runAllAutoImageFileToolButton.setObjectName(_fromUtf8("runAllAutoImageFileToolButton"))
        self.gridLayout_6.addWidget(self.runAllAutoImageFileToolButton, 3, 4, 1, 1)
        self.runAllAutoOutputDirCheckBox = QtGui.QCheckBox(self.runAllAutoTab)
        self.runAllAutoOutputDirCheckBox.setObjectName(_fromUtf8("runAllAutoOutputDirCheckBox"))
        self.gridLayout_6.addWidget(self.runAllAutoOutputDirCheckBox, 4, 0, 1, 1)
        self.runAllAutoOutputDirLabel = QtGui.QLabel(self.runAllAutoTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllAutoOutputDirLabel.setFont(font)
        self.runAllAutoOutputDirLabel.setObjectName(_fromUtf8("runAllAutoOutputDirLabel"))
        self.gridLayout_6.addWidget(self.runAllAutoOutputDirLabel, 5, 0, 1, 2)
        self.runAllAutoOutputDirToolButton = QtGui.QToolButton(self.runAllAutoTab)
        self.runAllAutoOutputDirToolButton.setObjectName(_fromUtf8("runAllAutoOutputDirToolButton"))
        self.gridLayout_6.addWidget(self.runAllAutoOutputDirToolButton, 6, 4, 1, 1)
        self.runAllAutoDisableFiwalkXLSXCheck = QtGui.QCheckBox(self.runAllAutoTab)
        self.runAllAutoDisableFiwalkXLSXCheck.setObjectName(_fromUtf8("runAllAutoDisableFiwalkXLSXCheck"))
        self.gridLayout_6.addWidget(self.runAllAutoDisableFiwalkXLSXCheck, 7, 0, 1, 2)
        self.runAllAutoDisableAnnotatedXLSXCheck = QtGui.QCheckBox(self.runAllAutoTab)
        self.runAllAutoDisableAnnotatedXLSXCheck.setObjectName(_fromUtf8("runAllAutoDisableAnnotatedXLSXCheck"))
        self.gridLayout_6.addWidget(self.runAllAutoDisableAnnotatedXLSXCheck, 8, 0, 1, 2)
        self.runAllAutoDisablePDFCheck = QtGui.QCheckBox(self.runAllAutoTab)
        self.runAllAutoDisablePDFCheck.setObjectName(_fromUtf8("runAllAutoDisablePDFCheck"))
        self.gridLayout_6.addWidget(self.runAllAutoDisablePDFCheck, 9, 0, 1, 2)
        self.runAllAutoTextEditLabel = QtGui.QLabel(self.runAllAutoTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.runAllAutoTextEditLabel.setFont(font)
        self.runAllAutoTextEditLabel.setObjectName(_fromUtf8("runAllAutoTextEditLabel"))
        self.gridLayout_6.addWidget(self.runAllAutoTextEditLabel, 10, 0, 1, 1)
        self.runAllAutoProgress = QtGui.QProgressBar(self.runAllAutoTab)
        self.runAllAutoProgress.setMaximum(1)
        self.runAllAutoProgress.setProperty("value", -1)
        self.runAllAutoProgress.setObjectName(_fromUtf8("runAllAutoProgress"))
        self.gridLayout_6.addWidget(self.runAllAutoProgress, 12, 0, 1, 1)
        self.runAllAutoClose = QtGui.QPushButton(self.runAllAutoTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAllAutoClose.sizePolicy().hasHeightForWidth())
        self.runAllAutoClose.setSizePolicy(sizePolicy)
        self.runAllAutoClose.setObjectName(_fromUtf8("runAllAutoClose"))
        self.gridLayout_6.addWidget(self.runAllAutoClose, 12, 1, 1, 1)
        self.runAllAutoCancel = QtGui.QPushButton(self.runAllAutoTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAllAutoCancel.sizePolicy().hasHeightForWidth())
        self.runAllAutoCancel.setSizePolicy(sizePolicy)
        self.runAllAutoCancel.setObjectName(_fromUtf8("runAllAutoCancel"))
        self.gridLayout_6.addWidget(self.runAllAutoCancel, 12, 2, 1, 1)
        self.runAllAutoRun = QtGui.QPushButton(self.runAllAutoTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAllAutoRun.sizePolicy().hasHeightForWidth())
        self.runAllAutoRun.setSizePolicy(sizePolicy)
        self.runAllAutoRun.setObjectName(_fromUtf8("runAllAutoRun"))
        self.gridLayout_6.addWidget(self.runAllAutoRun, 12, 3, 1, 1)
        self.runAllAutoImageFileLineEdit = QtGui.QLineEdit(self.runAllAutoTab)
        self.runAllAutoImageFileLineEdit.setMaxLength(0)
        self.runAllAutoImageFileLineEdit.setObjectName(_fromUtf8("runAllAutoImageFileLineEdit"))
        self.gridLayout_6.addWidget(self.runAllAutoImageFileLineEdit, 3, 0, 1, 4)
        self.runAllAutoOutputDirLineEdit = QtGui.QLineEdit(self.runAllAutoTab)
        self.runAllAutoOutputDirLineEdit.setObjectName(_fromUtf8("runAllAutoOutputDirLineEdit"))
        self.gridLayout_6.addWidget(self.runAllAutoOutputDirLineEdit, 6, 0, 1, 4)
        self.runAllAutoTextEdit = QtGui.QTextEdit(self.runAllAutoTab)
        self.runAllAutoTextEdit.setAutoFillBackground(True)
        self.runAllAutoTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.runAllAutoTextEdit.setObjectName(_fromUtf8("runAllAutoTextEdit"))
        self.gridLayout_6.addWidget(self.runAllAutoTextEdit, 11, 0, 1, 4)
        self.tabWidget.addTab(self.runAllAutoTab, _fromUtf8(""))
        self.fiwalkTab = QtGui.QWidget()
        self.fiwalkTab.setObjectName(_fromUtf8("fiwalkTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.fiwalkTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.fiwalkHeaderLabel = QtGui.QLabel(self.fiwalkTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.fiwalkHeaderLabel.setFont(font)
        self.fiwalkHeaderLabel.setWordWrap(True)
        self.fiwalkHeaderLabel.setObjectName(_fromUtf8("fiwalkHeaderLabel"))
        self.gridLayout_3.addWidget(self.fiwalkHeaderLabel, 0, 0, 1, 5)
        self.fiwalkImageFileLabel = QtGui.QLabel(self.fiwalkTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiwalkImageFileLabel.setFont(font)
        self.fiwalkImageFileLabel.setObjectName(_fromUtf8("fiwalkImageFileLabel"))
        self.gridLayout_3.addWidget(self.fiwalkImageFileLabel, 1, 0, 1, 1)
        self.fiwalkImageFileToolButton = QtGui.QToolButton(self.fiwalkTab)
        self.fiwalkImageFileToolButton.setObjectName(_fromUtf8("fiwalkImageFileToolButton"))
        self.gridLayout_3.addWidget(self.fiwalkImageFileToolButton, 2, 4, 1, 1)
        self.fiwalkOutputFileCheckBox = QtGui.QCheckBox(self.fiwalkTab)
        self.fiwalkOutputFileCheckBox.setObjectName(_fromUtf8("fiwalkOutputFileCheckBox"))
        self.gridLayout_3.addWidget(self.fiwalkOutputFileCheckBox, 3, 0, 1, 1)
        self.fiwalkOutputFileLabel = QtGui.QLabel(self.fiwalkTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiwalkOutputFileLabel.setFont(font)
        self.fiwalkOutputFileLabel.setObjectName(_fromUtf8("fiwalkOutputFileLabel"))
        self.gridLayout_3.addWidget(self.fiwalkOutputFileLabel, 4, 0, 1, 2)
        self.fiwalkOutputFileToolButton = QtGui.QToolButton(self.fiwalkTab)
        self.fiwalkOutputFileToolButton.setObjectName(_fromUtf8("fiwalkOutputFileToolButton"))
        self.gridLayout_3.addWidget(self.fiwalkOutputFileToolButton, 5, 4, 1, 1)
        self.fiwalkFormatCheck = QtGui.QCheckBox(self.fiwalkTab)
        self.fiwalkFormatCheck.setChecked(True)
        self.fiwalkFormatCheck.setObjectName(_fromUtf8("fiwalkFormatCheck"))
        self.gridLayout_3.addWidget(self.fiwalkFormatCheck, 6, 0, 1, 2)
        self.fiwalkMD5Check = QtGui.QCheckBox(self.fiwalkTab)
        self.fiwalkMD5Check.setChecked(True)
        self.fiwalkMD5Check.setObjectName(_fromUtf8("fiwalkMD5Check"))
        self.gridLayout_3.addWidget(self.fiwalkMD5Check, 7, 0, 1, 2)
        self.fiwalkSHACheck = QtGui.QCheckBox(self.fiwalkTab)
        self.fiwalkSHACheck.setObjectName(_fromUtf8("fiwalkSHACheck"))
        self.gridLayout_3.addWidget(self.fiwalkSHACheck, 8, 0, 1, 2)
        self.fiwalkTextEditLabel = QtGui.QLabel(self.fiwalkTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiwalkTextEditLabel.setFont(font)
        self.fiwalkTextEditLabel.setObjectName(_fromUtf8("fiwalkTextEditLabel"))
        self.gridLayout_3.addWidget(self.fiwalkTextEditLabel, 9, 0, 1, 1)
        self.fiwalkProgress = QtGui.QProgressBar(self.fiwalkTab)
        self.fiwalkProgress.setMaximum(1)
        self.fiwalkProgress.setProperty("value", -1)
        self.fiwalkProgress.setObjectName(_fromUtf8("fiwalkProgress"))
        self.gridLayout_3.addWidget(self.fiwalkProgress, 11, 0, 1, 1)
        self.fiwalkClose = QtGui.QPushButton(self.fiwalkTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fiwalkClose.sizePolicy().hasHeightForWidth())
        self.fiwalkClose.setSizePolicy(sizePolicy)
        self.fiwalkClose.setObjectName(_fromUtf8("fiwalkClose"))
        self.gridLayout_3.addWidget(self.fiwalkClose, 11, 1, 1, 1)
        self.fiwalkCancel = QtGui.QPushButton(self.fiwalkTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fiwalkCancel.sizePolicy().hasHeightForWidth())
        self.fiwalkCancel.setSizePolicy(sizePolicy)
        self.fiwalkCancel.setObjectName(_fromUtf8("fiwalkCancel"))
        self.gridLayout_3.addWidget(self.fiwalkCancel, 11, 2, 1, 1)
        self.fiwalkRun = QtGui.QPushButton(self.fiwalkTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fiwalkRun.sizePolicy().hasHeightForWidth())
        self.fiwalkRun.setSizePolicy(sizePolicy)
        self.fiwalkRun.setObjectName(_fromUtf8("fiwalkRun"))
        self.gridLayout_3.addWidget(self.fiwalkRun, 11, 3, 1, 1)
        self.fiwalkImageFileLineEdit = QtGui.QLineEdit(self.fiwalkTab)
        self.fiwalkImageFileLineEdit.setObjectName(_fromUtf8("fiwalkImageFileLineEdit"))
        self.gridLayout_3.addWidget(self.fiwalkImageFileLineEdit, 2, 0, 1, 4)
        self.fiwalkOutputFileLineEdit = QtGui.QLineEdit(self.fiwalkTab)
        self.fiwalkOutputFileLineEdit.setObjectName(_fromUtf8("fiwalkOutputFileLineEdit"))
        self.gridLayout_3.addWidget(self.fiwalkOutputFileLineEdit, 5, 0, 1, 4)
        self.fiwalkTextEdit = QtGui.QTextEdit(self.fiwalkTab)
        self.fiwalkTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.fiwalkTextEdit.setObjectName(_fromUtf8("fiwalkTextEdit"))
        self.gridLayout_3.addWidget(self.fiwalkTextEdit, 10, 0, 1, 4)
        self.tabWidget.addTab(self.fiwalkTab, _fromUtf8(""))
        self.fiwalkBatchTab = QtGui.QWidget()
        self.fiwalkBatchTab.setObjectName(_fromUtf8("fiwalkBatchTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.fiwalkBatchTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.fiwalkBatchHeaderLabel = QtGui.QLabel(self.fiwalkBatchTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.fiwalkBatchHeaderLabel.setFont(font)
        self.fiwalkBatchHeaderLabel.setWordWrap(True)
        self.fiwalkBatchHeaderLabel.setObjectName(_fromUtf8("fiwalkBatchHeaderLabel"))
        self.gridLayout_5.addWidget(self.fiwalkBatchHeaderLabel, 0, 0, 1, 5)
        self.fiwalkBatchImageLabel = QtGui.QLabel(self.fiwalkBatchTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiwalkBatchImageLabel.setFont(font)
        self.fiwalkBatchImageLabel.setObjectName(_fromUtf8("fiwalkBatchImageLabel"))
        self.gridLayout_5.addWidget(self.fiwalkBatchImageLabel, 1, 0, 1, 1)
        self.fiwalkBatchImageToolButton = QtGui.QToolButton(self.fiwalkBatchTab)
        self.fiwalkBatchImageToolButton.setObjectName(_fromUtf8("fiwalkBatchImageToolButton"))
        self.gridLayout_5.addWidget(self.fiwalkBatchImageToolButton, 2, 4, 1, 1)
        self.fiwalkBatchCustomDirCheck = QtGui.QCheckBox(self.fiwalkBatchTab)
        self.fiwalkBatchCustomDirCheck.setObjectName(_fromUtf8("fiwalkBatchCustomDirCheck"))
        self.gridLayout_5.addWidget(self.fiwalkBatchCustomDirCheck, 3, 0, 1, 1)
        self.fiwalkBatchCustomDirLabel = QtGui.QLabel(self.fiwalkBatchTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiwalkBatchCustomDirLabel.setFont(font)
        self.fiwalkBatchCustomDirLabel.setObjectName(_fromUtf8("fiwalkBatchCustomDirLabel"))
        self.gridLayout_5.addWidget(self.fiwalkBatchCustomDirLabel, 4, 0, 1, 2)
        self.fiwalkBatchCustomDirToolButton = QtGui.QToolButton(self.fiwalkBatchTab)
        self.fiwalkBatchCustomDirToolButton.setObjectName(_fromUtf8("fiwalkBatchCustomDirToolButton"))
        self.gridLayout_5.addWidget(self.fiwalkBatchCustomDirToolButton, 5, 4, 1, 1)
        self.fiwalkBatchFormatCheck = QtGui.QCheckBox(self.fiwalkBatchTab)
        self.fiwalkBatchFormatCheck.setChecked(True)
        self.fiwalkBatchFormatCheck.setObjectName(_fromUtf8("fiwalkBatchFormatCheck"))
        self.gridLayout_5.addWidget(self.fiwalkBatchFormatCheck, 6, 0, 1, 2)
        self.fiwalkBatchMD5Check = QtGui.QCheckBox(self.fiwalkBatchTab)
        self.fiwalkBatchMD5Check.setChecked(True)
        self.fiwalkBatchMD5Check.setObjectName(_fromUtf8("fiwalkBatchMD5Check"))
        self.gridLayout_5.addWidget(self.fiwalkBatchMD5Check, 7, 0, 1, 2)
        self.fiwalkBatchSHACheck = QtGui.QCheckBox(self.fiwalkBatchTab)
        self.fiwalkBatchSHACheck.setObjectName(_fromUtf8("fiwalkBatchSHACheck"))
        self.gridLayout_5.addWidget(self.fiwalkBatchSHACheck, 8, 0, 1, 2)
        self.fiwalkBatchTextEditLabel = QtGui.QLabel(self.fiwalkBatchTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fiwalkBatchTextEditLabel.setFont(font)
        self.fiwalkBatchTextEditLabel.setObjectName(_fromUtf8("fiwalkBatchTextEditLabel"))
        self.gridLayout_5.addWidget(self.fiwalkBatchTextEditLabel, 9, 0, 1, 1)
        self.fiwalkBatchProgress = QtGui.QProgressBar(self.fiwalkBatchTab)
        self.fiwalkBatchProgress.setMaximum(1)
        self.fiwalkBatchProgress.setProperty("value", -1)
        self.fiwalkBatchProgress.setObjectName(_fromUtf8("fiwalkBatchProgress"))
        self.gridLayout_5.addWidget(self.fiwalkBatchProgress, 11, 0, 1, 1)
        self.fiwalkBatchClose = QtGui.QPushButton(self.fiwalkBatchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fiwalkBatchClose.sizePolicy().hasHeightForWidth())
        self.fiwalkBatchClose.setSizePolicy(sizePolicy)
        self.fiwalkBatchClose.setObjectName(_fromUtf8("fiwalkBatchClose"))
        self.gridLayout_5.addWidget(self.fiwalkBatchClose, 11, 1, 1, 1)
        self.fiwalkBatchCancel = QtGui.QPushButton(self.fiwalkBatchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fiwalkBatchCancel.sizePolicy().hasHeightForWidth())
        self.fiwalkBatchCancel.setSizePolicy(sizePolicy)
        self.fiwalkBatchCancel.setObjectName(_fromUtf8("fiwalkBatchCancel"))
        self.gridLayout_5.addWidget(self.fiwalkBatchCancel, 11, 2, 1, 1)
        self.fiwalkBatchRun = QtGui.QPushButton(self.fiwalkBatchTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fiwalkBatchRun.sizePolicy().hasHeightForWidth())
        self.fiwalkBatchRun.setSizePolicy(sizePolicy)
        self.fiwalkBatchRun.setObjectName(_fromUtf8("fiwalkBatchRun"))
        self.gridLayout_5.addWidget(self.fiwalkBatchRun, 11, 3, 1, 1)
        self.fiwalkBatchTextEdit = QtGui.QTextEdit(self.fiwalkBatchTab)
        self.fiwalkBatchTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.fiwalkBatchTextEdit.setObjectName(_fromUtf8("fiwalkBatchTextEdit"))
        self.gridLayout_5.addWidget(self.fiwalkBatchTextEdit, 10, 0, 1, 4)
        self.fiwalkBatchCustomDirLineEdit = QtGui.QLineEdit(self.fiwalkBatchTab)
        self.fiwalkBatchCustomDirLineEdit.setObjectName(_fromUtf8("fiwalkBatchCustomDirLineEdit"))
        self.gridLayout_5.addWidget(self.fiwalkBatchCustomDirLineEdit, 5, 0, 1, 4)
        self.fiwalkBatchImageLineEdit = QtGui.QLineEdit(self.fiwalkBatchTab)
        self.fiwalkBatchImageLineEdit.setText(_fromUtf8(""))
        self.fiwalkBatchImageLineEdit.setObjectName(_fromUtf8("fiwalkBatchImageLineEdit"))
        self.gridLayout_5.addWidget(self.fiwalkBatchImageLineEdit, 2, 0, 1, 4)
        self.tabWidget.addTab(self.fiwalkBatchTab, _fromUtf8(""))
        self.annTab = QtGui.QWidget()
        self.annTab.setObjectName(_fromUtf8("annTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.annTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.annHeaderLabel = QtGui.QLabel(self.annTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.annHeaderLabel.setFont(font)
        self.annHeaderLabel.setWordWrap(True)
        self.annHeaderLabel.setObjectName(_fromUtf8("annHeaderLabel"))
        self.gridLayout_4.addWidget(self.annHeaderLabel, 0, 0, 1, 5)
        self.annImageLabel = QtGui.QLabel(self.annTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annImageLabel.setFont(font)
        self.annImageLabel.setObjectName(_fromUtf8("annImageLabel"))
        self.gridLayout_4.addWidget(self.annImageLabel, 1, 0, 1, 1)
        self.annImageToolButton = QtGui.QToolButton(self.annTab)
        self.annImageToolButton.setObjectName(_fromUtf8("annImageToolButton"))
        self.gridLayout_4.addWidget(self.annImageToolButton, 2, 4, 1, 1)
        self.annBEFeatureLabel = QtGui.QLabel(self.annTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annBEFeatureLabel.setFont(font)
        self.annBEFeatureLabel.setObjectName(_fromUtf8("annBEFeatureLabel"))
        self.gridLayout_4.addWidget(self.annBEFeatureLabel, 3, 0, 1, 1)
        self.annBEFeatureToolButton = QtGui.QToolButton(self.annTab)
        self.annBEFeatureToolButton.setObjectName(_fromUtf8("annBEFeatureToolButton"))
        self.gridLayout_4.addWidget(self.annBEFeatureToolButton, 4, 4, 1, 1)
        self.annOutDirLabel = QtGui.QLabel(self.annTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annOutDirLabel.setFont(font)
        self.annOutDirLabel.setObjectName(_fromUtf8("annOutDirLabel"))
        self.gridLayout_4.addWidget(self.annOutDirLabel, 5, 0, 1, 1)
        self.annOutDirToolButton = QtGui.QToolButton(self.annTab)
        self.annOutDirToolButton.setObjectName(_fromUtf8("annOutDirToolButton"))
        self.gridLayout_4.addWidget(self.annOutDirToolButton, 6, 4, 1, 1)
        self.annBEPyDirLabel = QtGui.QLabel(self.annTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annBEPyDirLabel.setFont(font)
        self.annBEPyDirLabel.setObjectName(_fromUtf8("annBEPyDirLabel"))
        self.gridLayout_4.addWidget(self.annBEPyDirLabel, 7, 0, 1, 1)
        self.annBEPyDirToolButton = QtGui.QToolButton(self.annTab)
        self.annBEPyDirToolButton.setObjectName(_fromUtf8("annBEPyDirToolButton"))
        self.gridLayout_4.addWidget(self.annBEPyDirToolButton, 8, 4, 1, 1)
        self.annBETextEditLabel = QtGui.QLabel(self.annTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.annBETextEditLabel.setFont(font)
        self.annBETextEditLabel.setObjectName(_fromUtf8("annBETextEditLabel"))
        self.gridLayout_4.addWidget(self.annBETextEditLabel, 9, 0, 1, 1)
        self.annProgress = QtGui.QProgressBar(self.annTab)
        self.annProgress.setMaximum(1)
        self.annProgress.setProperty("value", -1)
        self.annProgress.setObjectName(_fromUtf8("annProgress"))
        self.gridLayout_4.addWidget(self.annProgress, 11, 0, 1, 1)
        self.annClose = QtGui.QPushButton(self.annTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.annClose.sizePolicy().hasHeightForWidth())
        self.annClose.setSizePolicy(sizePolicy)
        self.annClose.setObjectName(_fromUtf8("annClose"))
        self.gridLayout_4.addWidget(self.annClose, 11, 1, 1, 1)
        self.annCancel = QtGui.QPushButton(self.annTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.annCancel.sizePolicy().hasHeightForWidth())
        self.annCancel.setSizePolicy(sizePolicy)
        self.annCancel.setObjectName(_fromUtf8("annCancel"))
        self.gridLayout_4.addWidget(self.annCancel, 11, 2, 1, 1)
        self.annRun = QtGui.QPushButton(self.annTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.annRun.sizePolicy().hasHeightForWidth())
        self.annRun.setSizePolicy(sizePolicy)
        self.annRun.setObjectName(_fromUtf8("annRun"))
        self.gridLayout_4.addWidget(self.annRun, 11, 3, 1, 1)
        self.annBETextEdit = QtGui.QTextEdit(self.annTab)
        self.annBETextEdit.setAutoFillBackground(True)
        self.annBETextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.annBETextEdit.setObjectName(_fromUtf8("annBETextEdit"))
        self.gridLayout_4.addWidget(self.annBETextEdit, 10, 0, 1, 4)
        self.annBEPyDirLineEdit = QtGui.QLineEdit(self.annTab)
        self.annBEPyDirLineEdit.setText(_fromUtf8(""))
        self.annBEPyDirLineEdit.setObjectName(_fromUtf8("annBEPyDirLineEdit"))
        self.gridLayout_4.addWidget(self.annBEPyDirLineEdit, 8, 0, 1, 4)
        self.annOutDirLineEdit = QtGui.QLineEdit(self.annTab)
        self.annOutDirLineEdit.setObjectName(_fromUtf8("annOutDirLineEdit"))
        self.gridLayout_4.addWidget(self.annOutDirLineEdit, 6, 0, 1, 4)
        self.annBEFeatureLineEdit = QtGui.QLineEdit(self.annTab)
        self.annBEFeatureLineEdit.setText(_fromUtf8(""))
        self.annBEFeatureLineEdit.setObjectName(_fromUtf8("annBEFeatureLineEdit"))
        self.gridLayout_4.addWidget(self.annBEFeatureLineEdit, 4, 0, 1, 4)
        self.annImageLineEdit = QtGui.QLineEdit(self.annTab)
        self.annImageLineEdit.setText(_fromUtf8(""))
        self.annImageLineEdit.setObjectName(_fromUtf8("annImageLineEdit"))
        self.gridLayout_4.addWidget(self.annImageLineEdit, 2, 0, 1, 4)
        self.tabWidget.addTab(self.annTab, _fromUtf8(""))
        self.reportsTab = QtGui.QWidget()
        self.reportsTab.setObjectName(_fromUtf8("reportsTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.reportsTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.reportsHeaderLabel = QtGui.QLabel(self.reportsTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.reportsHeaderLabel.setFont(font)
        self.reportsHeaderLabel.setWordWrap(True)
        self.reportsHeaderLabel.setObjectName(_fromUtf8("reportsHeaderLabel"))
        self.gridLayout_2.addWidget(self.reportsHeaderLabel, 0, 0, 1, 5)
        self.reportsFiwalkLabel = QtGui.QLabel(self.reportsTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reportsFiwalkLabel.setFont(font)
        self.reportsFiwalkLabel.setObjectName(_fromUtf8("reportsFiwalkLabel"))
        self.gridLayout_2.addWidget(self.reportsFiwalkLabel, 1, 0, 1, 1)
        self.reportsFiwalkToolButton = QtGui.QToolButton(self.reportsTab)
        self.reportsFiwalkToolButton.setObjectName(_fromUtf8("reportsFiwalkToolButton"))
        self.gridLayout_2.addWidget(self.reportsFiwalkToolButton, 2, 4, 1, 1)
        self.reportsAnnDirLabel = QtGui.QLabel(self.reportsTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reportsAnnDirLabel.setFont(font)
        self.reportsAnnDirLabel.setObjectName(_fromUtf8("reportsAnnDirLabel"))
        self.gridLayout_2.addWidget(self.reportsAnnDirLabel, 3, 0, 1, 1)
        self.reportsAnnDirToolButton = QtGui.QToolButton(self.reportsTab)
        self.reportsAnnDirToolButton.setObjectName(_fromUtf8("reportsAnnDirToolButton"))
        self.gridLayout_2.addWidget(self.reportsAnnDirToolButton, 4, 4, 1, 1)
        self.reportsOutDirLabel = QtGui.QLabel(self.reportsTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reportsOutDirLabel.setFont(font)
        self.reportsOutDirLabel.setObjectName(_fromUtf8("reportsOutDirLabel"))
        self.gridLayout_2.addWidget(self.reportsOutDirLabel, 5, 0, 1, 1)
        self.reportsOutDirToolButton = QtGui.QToolButton(self.reportsTab)
        self.reportsOutDirToolButton.setObjectName(_fromUtf8("reportsOutDirToolButton"))
        self.gridLayout_2.addWidget(self.reportsOutDirToolButton, 6, 4, 1, 1)
        self.reportsConfigLabel = QtGui.QLabel(self.reportsTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reportsConfigLabel.setFont(font)
        self.reportsConfigLabel.setObjectName(_fromUtf8("reportsConfigLabel"))
        self.gridLayout_2.addWidget(self.reportsConfigLabel, 7, 0, 1, 1)
        self.reportsCOnfigFileToolButton = QtGui.QToolButton(self.reportsTab)
        self.reportsCOnfigFileToolButton.setObjectName(_fromUtf8("reportsCOnfigFileToolButton"))
        self.gridLayout_2.addWidget(self.reportsCOnfigFileToolButton, 8, 4, 1, 1)
        self.reportsTextEditLabel = QtGui.QLabel(self.reportsTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reportsTextEditLabel.setFont(font)
        self.reportsTextEditLabel.setObjectName(_fromUtf8("reportsTextEditLabel"))
        self.gridLayout_2.addWidget(self.reportsTextEditLabel, 9, 0, 1, 1)
        self.reportsProgress = QtGui.QProgressBar(self.reportsTab)
        self.reportsProgress.setMaximum(1)
        self.reportsProgress.setProperty("value", -1)
        self.reportsProgress.setObjectName(_fromUtf8("reportsProgress"))
        self.gridLayout_2.addWidget(self.reportsProgress, 11, 0, 1, 1)
        self.reportsClose = QtGui.QPushButton(self.reportsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportsClose.sizePolicy().hasHeightForWidth())
        self.reportsClose.setSizePolicy(sizePolicy)
        self.reportsClose.setObjectName(_fromUtf8("reportsClose"))
        self.gridLayout_2.addWidget(self.reportsClose, 11, 1, 1, 1)
        self.reportsCancel = QtGui.QPushButton(self.reportsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportsCancel.sizePolicy().hasHeightForWidth())
        self.reportsCancel.setSizePolicy(sizePolicy)
        self.reportsCancel.setObjectName(_fromUtf8("reportsCancel"))
        self.gridLayout_2.addWidget(self.reportsCancel, 11, 2, 1, 1)
        self.reportsRun = QtGui.QPushButton(self.reportsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportsRun.sizePolicy().hasHeightForWidth())
        self.reportsRun.setSizePolicy(sizePolicy)
        self.reportsRun.setObjectName(_fromUtf8("reportsRun"))
        self.gridLayout_2.addWidget(self.reportsRun, 11, 3, 1, 1)
        self.reportsTextEdit = QtGui.QTextEdit(self.reportsTab)
        self.reportsTextEdit.setAutoFillBackground(True)
        self.reportsTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.reportsTextEdit.setObjectName(_fromUtf8("reportsTextEdit"))
        self.gridLayout_2.addWidget(self.reportsTextEdit, 10, 0, 1, 4)
        self.reportsConfigLineEdit = QtGui.QLineEdit(self.reportsTab)
        self.reportsConfigLineEdit.setObjectName(_fromUtf8("reportsConfigLineEdit"))
        self.gridLayout_2.addWidget(self.reportsConfigLineEdit, 8, 0, 1, 4)
        self.reportsOutDirLineEdit = QtGui.QLineEdit(self.reportsTab)
        self.reportsOutDirLineEdit.setObjectName(_fromUtf8("reportsOutDirLineEdit"))
        self.gridLayout_2.addWidget(self.reportsOutDirLineEdit, 6, 0, 1, 4)
        self.reportsAnnDirLineEdit = QtGui.QLineEdit(self.reportsTab)
        self.reportsAnnDirLineEdit.setText(_fromUtf8(""))
        self.reportsAnnDirLineEdit.setObjectName(_fromUtf8("reportsAnnDirLineEdit"))
        self.gridLayout_2.addWidget(self.reportsAnnDirLineEdit, 4, 0, 1, 4)
        self.reportsFiwalkLineEdit = QtGui.QLineEdit(self.reportsTab)
        self.reportsFiwalkLineEdit.setText(_fromUtf8(""))
        self.reportsFiwalkLineEdit.setObjectName(_fromUtf8("reportsFiwalkLineEdit"))
        self.gridLayout_2.addWidget(self.reportsFiwalkLineEdit, 2, 0, 1, 4)
        self.tabWidget.addTab(self.reportsTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionShow_Help = QtGui.QAction(MainWindow)
        self.actionShow_Help.setObjectName(_fromUtf8("actionShow_Help"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuHelp.addAction(self.actionShow_Help)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.fiwalkImageFileLineEdit, self.fiwalkImageFileToolButton)
        MainWindow.setTabOrder(self.fiwalkImageFileToolButton, self.fiwalkOutputFileLineEdit)
        MainWindow.setTabOrder(self.fiwalkOutputFileLineEdit, self.fiwalkOutputFileToolButton)
        MainWindow.setTabOrder(self.fiwalkOutputFileToolButton, self.fiwalkTextEdit)
        MainWindow.setTabOrder(self.fiwalkTextEdit, self.fiwalkClose)
        MainWindow.setTabOrder(self.fiwalkClose, self.fiwalkCancel)
        MainWindow.setTabOrder(self.fiwalkCancel, self.fiwalkRun)
        MainWindow.setTabOrder(self.fiwalkRun, self.annImageLineEdit)
        MainWindow.setTabOrder(self.annImageLineEdit, self.annImageToolButton)
        MainWindow.setTabOrder(self.annImageToolButton, self.annBEFeatureLineEdit)
        MainWindow.setTabOrder(self.annBEFeatureLineEdit, self.annBEFeatureToolButton)
        MainWindow.setTabOrder(self.annBEFeatureToolButton, self.annOutDirLineEdit)
        MainWindow.setTabOrder(self.annOutDirLineEdit, self.annOutDirToolButton)
        MainWindow.setTabOrder(self.annOutDirToolButton, self.annBEPyDirLineEdit)
        MainWindow.setTabOrder(self.annBEPyDirLineEdit, self.annBEPyDirToolButton)
        MainWindow.setTabOrder(self.annBEPyDirToolButton, self.annBETextEdit)
        MainWindow.setTabOrder(self.annBETextEdit, self.annClose)
        MainWindow.setTabOrder(self.annClose, self.annCancel)
        MainWindow.setTabOrder(self.annCancel, self.annRun)
        MainWindow.setTabOrder(self.annRun, self.reportsFiwalkLineEdit)
        MainWindow.setTabOrder(self.reportsFiwalkLineEdit, self.reportsFiwalkToolButton)
        MainWindow.setTabOrder(self.reportsFiwalkToolButton, self.reportsAnnDirLineEdit)
        MainWindow.setTabOrder(self.reportsAnnDirLineEdit, self.reportsAnnDirToolButton)
        MainWindow.setTabOrder(self.reportsAnnDirToolButton, self.reportsOutDirLineEdit)
        MainWindow.setTabOrder(self.reportsOutDirLineEdit, self.reportsOutDirToolButton)
        MainWindow.setTabOrder(self.reportsOutDirToolButton, self.reportsConfigLineEdit)
        MainWindow.setTabOrder(self.reportsConfigLineEdit, self.reportsCOnfigFileToolButton)
        MainWindow.setTabOrder(self.reportsCOnfigFileToolButton, self.reportsTextEdit)
        MainWindow.setTabOrder(self.reportsTextEdit, self.reportsClose)
        MainWindow.setTabOrder(self.reportsClose, self.reportsCancel)
        MainWindow.setTabOrder(self.reportsCancel, self.reportsRun)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BitCurator Reporting Tool", None))
        self.runAllHeaderLabel.setText(_translate("MainWindow", "Run fiwalk, annotate the bulk_extractor output, and generate Office / PDF reports.", None))
        self.runAllBEViewerButton.setText(_translate("MainWindow", "Launch BEViewer", None))
        self.runAllImageFileLabel.setText(_translate("MainWindow", "Image File", None))
        self.runAllImageFileToolButton.setText(_translate("MainWindow", "...", None))
        self.runAllBEDirectoryToolButton.setText(_translate("MainWindow", "...", None))
        self.runAllOutputDirToolButton.setText(_translate("MainWindow", "...", None))
        self.runAllConfigToolButton.setText(_translate("MainWindow", "...", None))
        self.runAllTextEditLabel.setText(_translate("MainWindow", "Command Line Output", None))
        self.runAllClose.setText(_translate("MainWindow", "Close", None))
        self.runAllCancel.setText(_translate("MainWindow", "Cancel", None))
        self.runAllRun.setText(_translate("MainWindow", "Run", None))
        self.runAllConfigLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File", None))
        self.runAllLineEditLabel.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory", None))
        self.runAllBEDirectoryLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory", None))
        self.runAllImageFileLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File", None))
        self.runAllBEDirectoryLabel.setText(_translate("MainWindow", "Bulk Extractor Feature Directory", None))
        self.runAllOutputDirLabel.setText(_translate("MainWindow", "Output Directory (fiwalk output, annotated features, and reports will appear in here)", None))
        self.runaAllBEDescriptorLabel.setText(_translate("MainWindow", "If you haven\'t run bulk_extractor yet, use the button to the right to launch and run it first.", None))
        self.runAllConfigLabel.setText(_translate("MainWindow", "Config File (Optional)", None))
        self.runAllDisableFiwalkXLSXCheck.setText(_translate("MainWindow", "Disable fiwalk XLSX report (reduces runtime; DFXML will still be created)", None))
        self.runAllDisableAnnotatedXLSXCheck.setText(_translate("MainWindow", "Disable annotated features XLSX reports (reduces runtime)", None))
        self.runAllDisablePDFCheck.setText(_translate("MainWindow", "Disable PDF reports (reduces runtime)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.runAllTab), _translate("MainWindow", "Run All", None))
        self.runAllAutoHeaderLabel.setText(_translate("MainWindow", "Run fiwalk, annotate the bulk_extractor output, and generate Office / PDF reports.", None))
        self.runAllAutoDescriptorLabel.setText(_translate("MainWindow", "All tools, including bulk_extractor, will be run automatically with their default settings. By default, all reports will be placed in a new directory named [IMAGE_NAME]-reports in the directory in which the image is located. You may choose a different output directory using the option below.", None))
        self.runAllAutoImageFileLabel.setText(_translate("MainWindow", "Image File", None))
        self.runAllAutoImageFileToolButton.setText(_translate("MainWindow", "...", None))
        self.runAllAutoOutputDirCheckBox.setText(_translate("MainWindow", "Use Custom Output Directory", None))
        self.runAllAutoOutputDirLabel.setText(_translate("MainWindow", "Custom Output Directory (ignored unless checkbox is selected!)", None))
        self.runAllAutoOutputDirToolButton.setText(_translate("MainWindow", "...", None))
        self.runAllAutoDisableFiwalkXLSXCheck.setText(_translate("MainWindow", "Disable fiwalk XLSX report (DFXML will still be created)", None))
        self.runAllAutoDisableAnnotatedXLSXCheck.setText(_translate("MainWindow", "Disable annotated features XLSX reports", None))
        self.runAllAutoDisablePDFCheck.setText(_translate("MainWindow", "Disable PDF reports", None))
        self.runAllAutoTextEditLabel.setText(_translate("MainWindow", "Command Line Output", None))
        self.runAllAutoClose.setText(_translate("MainWindow", "Close", None))
        self.runAllAutoCancel.setText(_translate("MainWindow", "Cancel", None))
        self.runAllAutoRun.setText(_translate("MainWindow", "Run", None))
        self.runAllAutoImageFileLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File", None))
        self.runAllAutoOutputDirLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.runAllAutoTab), _translate("MainWindow", "Run All (Auto)", None))
        self.fiwalkHeaderLabel.setText(_translate("MainWindow", "Fiwalk produces a DFXML file showing the volumes, directories, and files contained within a disk image. Output is an XML file named [IMAGE_NAME].xml in the same directory unless otherwise specified.", None))
        self.fiwalkImageFileLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Image File</span></p></body></html>", None))
        self.fiwalkImageFileToolButton.setText(_translate("MainWindow", "...", None))
        self.fiwalkOutputFileCheckBox.setText(_translate("MainWindow", "Use Custom DFXML File Name", None))
        self.fiwalkOutputFileLabel.setText(_translate("MainWindow", "Custom DFXML File Name (ignored unless checkbox is selected!)", None))
        self.fiwalkOutputFileToolButton.setText(_translate("MainWindow", "...", None))
        self.fiwalkFormatCheck.setText(_translate("MainWindow", "Enable format identification using \'file\' (increases runtime)", None))
        self.fiwalkMD5Check.setText(_translate("MainWindow", "Enable MD5 checksums in output (increases runtime)", None))
        self.fiwalkSHACheck.setText(_translate("MainWindow", "Enable SHA256 checksums in output (increases runtime)", None))
        self.fiwalkTextEditLabel.setText(_translate("MainWindow", "Command line output:", None))
        self.fiwalkClose.setText(_translate("MainWindow", "Close", None))
        self.fiwalkCancel.setText(_translate("MainWindow", "Cancel", None))
        self.fiwalkRun.setText(_translate("MainWindow", "Run", None))
        self.fiwalkImageFileLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File", None))
        self.fiwalkOutputFileLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fiwalkTab), _translate("MainWindow", "Fiwalk", None))
        self.fiwalkBatchHeaderLabel.setText(_translate("MainWindow", "Fiwalk produces a DFXML file showing the volumes, directories, and files contained within a disk image. In this tab, you can point fiwalk at a directory containing one or more E01, AFF, or raw disk images. Output files will be named [IMAGE_NAME].xml", None))
        self.fiwalkBatchImageLabel.setText(_translate("MainWindow", "<html><head/><body><p>Directory Containing Image Files</p></body></html>", None))
        self.fiwalkBatchImageToolButton.setText(_translate("MainWindow", "...", None))
        self.fiwalkBatchCustomDirCheck.setText(_translate("MainWindow", "Use Custom Output Directory", None))
        self.fiwalkBatchCustomDirLabel.setText(_translate("MainWindow", "Custom Output Directory (ignored unless checkbox is selected!)", None))
        self.fiwalkBatchCustomDirToolButton.setText(_translate("MainWindow", "...", None))
        self.fiwalkBatchFormatCheck.setText(_translate("MainWindow", "Enable format identification using \'file\' (increases runtime)", None))
        self.fiwalkBatchMD5Check.setText(_translate("MainWindow", "Enable MD5 checksums in output (increases runtime)", None))
        self.fiwalkBatchSHACheck.setText(_translate("MainWindow", "Enable SHA256 checksums in output (increases runtime)", None))
        self.fiwalkBatchTextEditLabel.setText(_translate("MainWindow", "Command line output:", None))
        self.fiwalkBatchClose.setText(_translate("MainWindow", "Close", None))
        self.fiwalkBatchCancel.setText(_translate("MainWindow", "Cancel", None))
        self.fiwalkBatchRun.setText(_translate("MainWindow", "Run", None))
        self.fiwalkBatchCustomDirLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory", None))
        self.fiwalkBatchImageLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fiwalkBatchTab), _translate("MainWindow", "Fiwalk (Batch)", None))
        self.annHeaderLabel.setText(_translate("MainWindow", "Produces reports that identify which Bulk Extractor features are contained within files in a disk image", None))
        self.annImageLabel.setText(_translate("MainWindow", "Image File", None))
        self.annImageToolButton.setText(_translate("MainWindow", "...", None))
        self.annBEFeatureLabel.setText(_translate("MainWindow", "Bulk Extractor Feature Directory", None))
        self.annBEFeatureToolButton.setText(_translate("MainWindow", "...", None))
        self.annOutDirLabel.setText(_translate("MainWindow", "Annotated Feature Files Directory (new)", None))
        self.annOutDirToolButton.setText(_translate("MainWindow", "...", None))
        self.annBEPyDirLabel.setText(_translate("MainWindow", "Bulk Extractor Python Directory (optional)", None))
        self.annBEPyDirToolButton.setText(_translate("MainWindow", "...", None))
        self.annBETextEditLabel.setText(_translate("MainWindow", "Command Line Output", None))
        self.annClose.setText(_translate("MainWindow", "Close", None))
        self.annCancel.setText(_translate("MainWindow", "Cancel", None))
        self.annRun.setText(_translate("MainWindow", "Run", None))
        self.annBEPyDirLineEdit.setPlaceholderText(_translate("MainWindow", "/home/bcadmin/Tools/bulk_extractor/python", None))
        self.annOutDirLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory", None))
        self.annBEFeatureLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory", None))
        self.annImageLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.annTab), _translate("MainWindow", "Annotate BE Reports", None))
        self.reportsHeaderLabel.setText(_translate("MainWindow", "Produces Office Open XML and PDF Reports to assist in Image Analysis", None))
        self.reportsFiwalkLabel.setText(_translate("MainWindow", "Fiwalk XML File", None))
        self.reportsFiwalkToolButton.setText(_translate("MainWindow", "...", None))
        self.reportsAnnDirLabel.setText(_translate("MainWindow", "Annotated Feature Files Directory", None))
        self.reportsAnnDirToolButton.setText(_translate("MainWindow", "...", None))
        self.reportsOutDirLabel.setText(_translate("MainWindow", "Output Directory for Reports", None))
        self.reportsOutDirToolButton.setText(_translate("MainWindow", "...", None))
        self.reportsConfigLabel.setText(_translate("MainWindow", "Config File (Optional)", None))
        self.reportsCOnfigFileToolButton.setText(_translate("MainWindow", "...", None))
        self.reportsTextEditLabel.setText(_translate("MainWindow", "Command Line Output", None))
        self.reportsClose.setText(_translate("MainWindow", "Close", None))
        self.reportsCancel.setText(_translate("MainWindow", "Cancel", None))
        self.reportsRun.setText(_translate("MainWindow", "Run", None))
        self.reportsConfigLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File", None))
        self.reportsOutDirLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory", None))
        self.reportsAnnDirLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/Directory", None))
        self.reportsFiwalkLineEdit.setPlaceholderText(_translate("MainWindow", "/Path/To/File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reportsTab), _translate("MainWindow", "Reports", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionCopy.setText(_translate("MainWindow", "Copy", None))
        self.actionCut.setText(_translate("MainWindow", "Cut", None))
        self.actionPaste.setText(_translate("MainWindow", "Paste", None))
        self.actionShow_Help.setText(_translate("MainWindow", "Show Help", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

